// Generated by dart2js, the Dart to JavaScript compiler.
(function($){var A={}
delete A.x
var B={}
delete B.x
var C={}
delete C.x
var D={}
delete D.x
var E={}
delete E.x
var F={}
delete F.x
var G={}
delete G.x
var H={}
delete H.x
var J={}
delete J.x
var K={}
delete K.x
var L={}
delete L.x
var M={}
delete M.x
var N={}
delete N.x
var O={}
delete O.x
var P={}
delete P.x
var Q={}
delete Q.x
var R={}
delete R.x
var S={}
delete S.x
var T={}
delete T.x
var U={}
delete U.x
var V={}
delete V.x
var W={}
delete W.x
var X={}
delete X.x
var Y={}
delete Y.x
var Z={}
delete Z.x
function I(){}
init()
$=I.p
var $$={}
$$.Br=[P,{"":"v;nq,Tu,Az",
call$2:function(a,b){return this.nq[this.Tu](a,b)},
call$1:function(a){return this.call$2(a,null)}}]
$$.EV=[P,{"":"v;nq,Tu,Az",
call$0:function(){return this.nq[this.Tu]()}}]
$$.fo=[H,{"":"Tp;call$2,$name"}]
$$.E8=[H,{"":"Tp;call$0,$name"}]
$$.oL=[H,{"":"Tp;call$5,$name"}]
$$.v8=[H,{"":"Tp;call$1,$name"}]
$$.EE=[H,{"":"Tp;call$1,$name"}]
$$.Q3=[H,{"":"Tp;call$1,$name"}]
$$.Pi=[H,{"":"Tp;call$1,$name"}]
$$.jU=[H,{"":"Tp;call$1,$name"}]
$$.eB=[H,{"":"Tp;call$1,$name"}]
$$.r7=[H,{"":"Tp;call$2,$name"}]
$$.EN=[P,{"":"Tp;call$0,$name"}]
$$.Xk=[P,{"":"Tp;call$2,$name"}]
$$.Wv=[P,{"":"Tp;call$1,$name"}]
$$.vb=[P,{"":"Tp;call$2,$name"}]
$$.FL=[M,{"":"Tp;call$0,$name"}]
$$.CW=[M,{"":"Tp;call$1,$name"}]
$$.pR=[M,{"":"Tp;call$1,$name"}]
;(function (reflectionData) {
  function map(x){x={x:x};delete x.x;return x}
  if (!init.libraries) init.libraries = [];
  if (!init.mangledNames) init.mangledNames = map();
  if (!init.mangledGlobalNames) init.mangledGlobalNames = map();
  if (!init.statics) init.statics = map();
  if (!init.interfaces) init.interfaces = map();
  if (!init.globalFunctions) init.globalFunctions = map();
  var libraries = init.libraries;
  var mangledNames = init.mangledNames;
  var mangledGlobalNames = init.mangledGlobalNames;
  var hasOwnProperty = Object.prototype.hasOwnProperty;
  var length = reflectionData.length;
  for (var i = 0; i < length; i++) {
    var data = reflectionData[i];
    var name = data[0];
    var uri = data[1];
    var metadata = data[2];
    var globalObject = data[3];
    var descriptor = data[4];
    var isRoot = !!data[5];
    var fields = descriptor && descriptor[""];
    var classes = [];
    var functions = [];
    function processStatics(descriptor) {
      for (var property in descriptor) {
        if (!hasOwnProperty.call(descriptor, property)) continue;
        if (property === "") continue;
        var element = descriptor[property];
        var firstChar = property.substring(0, 1);
        var previousProperty;
        if (firstChar === "+") {
          mangledGlobalNames[previousProperty] = property.substring(1);
          if (descriptor[property] == 1) descriptor[previousProperty].$reflectable = 1;
          if (element && element.length) init.interfaces[previousProperty] = element;
        } else if (firstChar === "@") {
          property = property.substring(1);
          $[property]["@"] = element;
        } else if (typeof element === "function") {
          globalObject[previousProperty = property] = element;
          functions.push(property);
          init.globalFunctions[property] = element;
        } else {
          previousProperty = property;
          var newDesc = {};
          var previousProp;
          for (var prop in element) {
            if (!hasOwnProperty.call(element, prop)) continue;
            firstChar = prop.substring(0, 1);
            if (prop === "static") {
              processStatics(init.statics[property] = element[prop]);
            } else if (firstChar === "+") {
              mangledNames[previousProp] = prop.substring(1);
              if (element[prop] == 1) element[previousProp].$reflectable = 1;
            } else if (firstChar === "@" && prop !== "@") {
              newDesc[prop.substring(1)]["@"] = element[prop];
            } else {
              newDesc[previousProp = prop] = element[prop];
            }
          }
          $$[property] = [globalObject, newDesc];
          classes.push(property);
        }
      }
    }
    processStatics(descriptor);
    libraries.push([name, uri, classes, functions, metadata, fields, isRoot,
                    globalObject]);
  }
})([["_foreign_helper","dart:_foreign_helper",,H,{FK:{"":"a;tT"}}],["_interceptors","dart:_interceptors",,J,{x:function(a){return void 0},Qu:function(a,b,c,d){return{i: a, p: b, e: c, x: d}},ks:function(a){var z,y,x
z=a[init.dispatchPropertyName]
if(z!=null){y=z.p
if(!1===y)return z.i
if(!0===y)return a
x=Object.getPrototypeOf(a)
if(y===x)return z.i
if(z.e===x)return y(a,z)}z=H.Px(a)
if(z==null)return C.Ku
Object.defineProperty(Object.getPrototypeOf(a), init.dispatchPropertyName, {value: z, enumerable: false, writable: true, configurable: true})
return J.ks(a)},vB:{"":"a;",
n:function(a,b){return a===b},
giO:function(a){return H.eQ(a)},
bu:function(a){return H.a5(a)}},kn:{"":"bool/vB;",
bu:function(a){return String(a)},
giO:function(a){return a?519018:218159},
$isbool:true},PE:{"":"vB;",
n:function(a,b){return null==b},
bu:function(a){return"null"},
giO:function(a){return 0}},Ue:{"":"vB;",
giO:function(a){return 0}},iC:{"":"Ue;"},kd:{"":"Ue;"},Q:{"":"List/vB;",
aN:function(a,b){return H.bQ(a,b)},
Zv:function(a,b){if(b>>>0!==b||b>=a.length)throw H.e(b)
return a[b]},
bu:function(a){return H.mx(a,"[","]")},
gA:function(a){return new H.a7(a,a.length,0,null)},
giO:function(a){return H.eQ(a)},
gB:function(a){return a.length},
t:function(a,b){if(typeof b!=="number"||Math.floor(b)!==b)throw H.b(new P.AT(b))
if(b>=a.length||b<0)throw H.b(new P.bJ("value "+H.d(b)))
return a[b]},
u:function(a,b,c){if(!!a.immutable$list)H.vh(new P.ub("indexed set"))
if(typeof b!=="number"||Math.floor(b)!==b)throw H.b(new P.AT(b))
if(b>=a.length||b<0)throw H.b(new P.bJ("value "+H.d(b)))
a[b]=c},
$isList:true,
$asvB:null,
$aszM:null,
$isList:true},nM:{"":"Q;",$isnM:true,
$asQ:function(){return[null]},
$aszM:function(){return[null]}},tN:{"":"nM;"},Jt:{"":"nM;"},P:{"":"num/vB;",
gzP:function(a){return a===0?1/a<0:a<0},
By:function(a,b){return a%b},
yu:function(a){var z
if(isNaN(a))throw H.b(new P.ub("NaN"))
if(a==Infinity||a==-Infinity)throw H.b(new P.ub("Infinity"))
z=a<0?Math.ceil(a):Math.floor(a)
return z==-0.0?0:z},
Hp:function(a){return a},
bu:function(a){if(a===0&&1/a<0)return"-0.0"
else return""+a},
giO:function(a){return a&0x1FFFFFFF},
W:function(a,b){if(typeof b!=="number")throw H.b(new P.AT(b))
return a-b},
Z:function(a,b){return this.yu(a/b)},
m:function(a,b){if(b<0)throw H.b(new P.AT(b))
if(a>0){if(b>31)return 0
return a>>>b}if(b>31)b=31
return a>>b>>>0},
C:function(a,b){if(typeof b!=="number")throw H.b(new P.AT(b))
return a<b},
D:function(a,b){if(typeof b!=="number")throw H.b(new P.AT(b))
return a>b},
F:function(a,b){if(typeof b!=="number")throw H.b(new P.AT(b))
return a>=b},
$isnum:true},im:{"":"int/P;",$isdouble:true,$isnum:true,$isint:true},VA:{"":"double/P;",$isdouble:true,$isnum:true},O:{"":"String/vB;",
j:function(a,b){if(b<0)throw H.b(new P.bJ("value "+H.d(b)))
if(b>=a.length)throw H.b(new P.bJ("value "+H.d(b)))
return a.charCodeAt(b)},
Nj:function(a,b,c){if(c==null)c=a.length
if(typeof c!=="number")H.vh(new P.AT(c))
if(b<0)throw H.b(new P.bJ("value "+b))
if(typeof c!=="number")throw H.s(c)
if(b>c)throw H.b(new P.bJ("value "+b))
if(c>a.length)throw H.b(new P.bJ("value "+H.d(c)))
return a.substring(b,c)},
yn:function(a,b){return this.Nj(a,b,null)},
gl0:function(a){return a.length===0},
bu:function(a){return a},
giO:function(a){var z,y,x
for(z=a.length,y=0,x=0;x<z;++x){y=536870911&y+a.charCodeAt(x)
y=536870911&y+((524287&y)<<10>>>0)
y^=y>>6}y=536870911&y+((67108863&y)<<3>>>0)
y^=y>>11
return 536870911&y+((16383&y)<<15>>>0)},
gB:function(a){return a.length},
t:function(a,b){if(typeof b!=="number"||Math.floor(b)!==b)throw H.b(new P.AT(b))
if(b>=a.length||b<0)throw H.b(new P.bJ("value "+H.d(b)))
return a[b]},
$isString:true}}],["_isolate_helper","dart:_isolate_helper",,H,{zd:function(a,b){var z=a.vV(b)
$globalState.Xz.bL()
return z},Rq:function(a){var z
$globalState=H.Zh(a)
if($globalState.EF===!0)return
z=H.TJ()
$globalState.yc=z
$globalState.N0=z
z.vV(a)
$globalState.Xz.bL()},Td:function(){var z=init.currentScript
if(z!=null)return String(z.src)
if(typeof version=="function"&&typeof os=="object"&&"system" in os)return H.ZV()
if(typeof version=="function"&&typeof system=="function")return thisFilename()
return},ZV:function(){var z,y
z=new Error().stack
if(z==null){z=(function() {try { throw new Error() } catch(e) { return e.stack }})()
if(z==null)throw H.b(new P.ub("No stack trace"))}y=z.match(new RegExp("^ *at [^(]*\\((.*):[0-9]*:[0-9]*\\)$","m"))
if(y!=null)return y[1]
y=z.match(new RegExp("^[^@]*@(.*):[0-9]*$","m"))
if(y!=null)return y[1]
throw H.b(new P.ub("Cannot extract URI from \""+z+"\""))},Mg:function(a,b){var z,y,x,w,v,u,t
z=H.Hh(b.data)
y=J.U6(z)
switch(y.t(z,"command")){case"start":$globalState.oL=y.t(z,"id")
x=y.t(z,"functionName")
w=x==null?$globalState.w2:init.globalFunctions[x]
v=H.Hh(y.t(z,"replyTo"))
u=H.TJ()
y=$globalState.Xz
y.SQ
y.Rk.PN(new H.IY(u,new H.jl(w,v),"worker-start"))
$globalState.N0=u
$globalState.Xz.bL()
break
case"spawn-worker":H.oT(y.t(z,"functionName"),y.t(z,"uri"),y.t(z,"replyPort"))
break
case"message":if(y.t(z,"port")!=null)y.t(z,"port").LV(y.t(z,"msg"),y.t(z,"replyTo"))
$globalState.Xz.bL()
break
case"close":y=$globalState.XC
t=$.p6()
y.Rz(y,t.t(t,a))
a.terminate()
$globalState.Xz.bL()
break
case"log":H.VL(y.t(z,"msg"))
break
case"print":if($globalState.EF===!0){y=$globalState.vd
t=H.Gy(H.Pd(["command","print","msg",z]))
y.K3
self.postMessage(t)}else H.ib(J.AG(y.t(z,"msg")))
break
case"error":throw H.b(y.t(z,"msg"))
default:}},VL:function(a){var z,y,x,w
if($globalState.EF===!0){y=$globalState.vd
x=H.Gy(H.Pd(["command","log","msg",a]))
y.K3
self.postMessage(x)}else try{$.jk().console.log(a)}catch(w){H.Ru(w)
z=new H.XO(w,null)
throw H.b(new P.HG(z))}},Z7:function(a,b){var z
H.Ql($globalState.N0.jO)
$.Dz=H.Ty()
z=P.WP()
z.tr
b.LV("spawned",new H.JM(z,$globalState.N0.jO))
a.call$0()},oT:function(a,b,c){var z,y,x
if(b==null)b=$.Rs()
z=new Worker(b)
z.onmessage=function(e) { H.NB.call$2(z, e); }
y=$globalState
x=y.Y7
y.Y7=x+1
y=$.p6()
y.u(y,z,x)
y=$globalState.XC
y.u(y,x,z)
z.postMessage(H.Gy(H.Pd(["command","start","id",x,"replyTo",H.Gy(c),"functionName",a])))},ff:function(a,b){var z=H.ZF()
z.h7(a)
P.pH(z.Gx).ml(new H.yc(b))},Gy:function(a){var z
if($globalState.ji===!0){z=new H.Bj(0,new H.X1())
z.Oj=new H.fP(null)
return z.h7(a)}else{z=new H.NO(new H.X1())
z.Oj=new H.fP(null)
return z.h7(a)}},Hh:function(a){if($globalState.ji===!0)return new H.II(null).QS(a)
else return a},vM:function(a){return a==null||typeof a==="string"||typeof a==="number"||typeof a==="boolean"},uu:function(a){return a==null||typeof a==="string"||typeof a==="number"||typeof a==="boolean"},NU:{"":"a;",$isNU:true},or:{"":"rE;NO,ZQ<",
n:function(a,b){var z
if(b==null)return!1
z=J.x(b)
return typeof b==="object"&&b!==null&&!!z.$isfj&&J.de(this.ZQ,b.gZQ())},
giO:function(a){return J.v1(this.ZQ)+499},
$isor:true,
$asfj:null,
$isfj:true},O2:{"":"a;Hg,oL,Y7,N0,yc,Xz,Ai,EF,ji,i2,vd,XC,w2",
Xa:function(){var z,y
z=$.C5()==null
y=$.Nl()
this.EF=z&&$.Iz()===!0
if(this.EF!==!0)y=y!=null&&$.Rs()!=null
else y=!0
this.ji=y
this.Ai=z&&this.EF!==!0},
kw:function(){var z=function (e) { H.NB.call$2(this.vd, e); }
$.jk().onmessage=z
$.jk().dartPrint = function (object) {}},
yX:function(a){this.Xa()
this.Xz=new H.cC(P.NZ(null,H.IY),0)
this.i2=P.L5(null,null,null,J.im,H.aX)
this.XC=P.L5(null,null,null,J.im,null)
if(this.EF===!0){this.vd=new H.JH()
this.kw()}},
static:{Zh:function(a){var z=new H.O2(0,0,1,null,null,null,null,null,null,null,null,null,a)
z.yX(a)
return z}}},aX:{"":"a;jO,Gx,En<",
vV:function(a){var z,y,x
z=$globalState.N0
$globalState.N0=this
$=this.En
y=null
try{y=a.call$0()}finally{$globalState.N0=z
if(z!=null){x=z
x.wS
$=x.gEn()}}return y},
Zt:function(a){var z=this.Gx
return z.t(z,a)},
mg:function(a,b,c){var z
if(this.Gx.x4(b))throw H.b(new P.HG("Registry: ports must be registered only once."))
z=this.Gx
z.u(z,b,c)
z=$globalState.i2
z.u(z,this.jO,this)},
Fb:function(a){var z=this.Gx
z.Rz(z,a)
if(this.Gx.iI===0){z=$globalState.i2
z.Rz(z,this.jO)}},
e1:function(){var z,y
z=$globalState
y=z.Hg
z.Hg=y+1
this.jO=y
this.Gx=P.L5(null,null,null,J.im,P.rR)
this.En=new I()},
static:{TJ:function(){var z=new H.aX(null,null,null)
z.e1()
return z}}},cC:{"":"a;Rk,bZ",
Jc:function(){var z=this.Rk
if(z.JV===z.D8)return
return z.Ux()},
LM:function(){if($globalState.yc!=null&&$globalState.i2.x4($globalState.yc.jO)&&$globalState.Ai===!0&&$globalState.yc.Gx.iI===0)throw H.b(new P.HG("Program exited with open ReceivePorts."))},
xB:function(){var z,y,x
z=this.Jc()
if(z==null){this.LM()
y=$globalState
if(y.EF===!0){x=y.i2
x.gl0
x=x.iI===0&&y.Xz.bZ===0}else x=!1
if(x){y=y.vd
x=H.Gy(H.Pd(["command","close"]))
y.K3
self.postMessage(x)}return!1}z.VU()
return!0},
uy:function(){if($.C5()!=null)new H.RA(this).call$0()
else for(;this.xB(););},
bL:function(){var z,y,x,w,v
if($globalState.EF!==!0)this.uy()
else try{this.uy()}catch(x){w=H.Ru(x)
z=w
y=new H.XO(x,null)
w=$globalState.vd
v=H.Gy(H.Pd(["command","error","msg",H.d(z)+"\n"+H.d(y)]))
w.K3
self.postMessage(v)}}},RA:{"":"Tp;a",
call$0:function(){var z,y
if(!this.a.xB())return
z=new P.qu($.o8(),this,null)
y=z.IF
y.Tl=y.Tl+1
z.dD=P.jL(C.RT,z.gRR())}},IY:{"":"a;od,i3,G1",
VU:function(){this.od.vV(this.i3)}},JH:{"":"a;"},jl:{"":"Tp;a,b",
call$0:function(){H.Z7(this.a,this.b)}},Iy:{"":"a;rD<",
yS:function(a){var z
if(a!=null){z=J.x(a)
z=(typeof a!=="object"||a===null||!z.$isJM)&&(typeof a!=="object"||a===null||!z.$isns)&&!0}else z=!1
if(z)throw H.b(new P.HG("SendPort.send: Illegal replyTo port type"))},
call$1:function(a){var z,y,x
z=null
y=new P.Zf(P.Dt(z))
H.VM(y,[z])
x=H.Ty()
this.LV(a,new H.JM(x,$globalState.N0.jO))
x.y8=new H.oG(y,x)
return y.MM},
$isbC:true},oG:{"":"Tp;a,b",
call$2:function(a,b){var z,y
z=this.b
z.y8=null
$globalState.N0.Fb(z.wY)
z=J.x(a)
y=this.a
if(typeof a==="object"&&a!==null&&!!z.$isQ4){z=y.MM
if(z.tj!==0)H.vh(new P.lj("Future already completed"))
z.iY(a,null)}else{z=y.MM
if(z.tj!==0)H.vh(new P.lj("Future already completed"))
z.EE(a)}}},JM:{"":"Iy;UU<,rD",
LV:function(a,b){H.ff([a,b],new H.Ua(this,a,b))},
n:function(a,b){var z
if(b==null)return!1
z=J.x(b)
return typeof b==="object"&&b!==null&&!!z.$isJM&&J.de(this.UU,b.UU)},
giO:function(a){return this.UU.gwY()},
$isJM:true,
$isbC:true},Ua:{"":"Tp;b,c,d",
call$0:function(){var z,y,x,w,v,u,t
z={}
y=this.b
x=this.d
y.yS(x)
w=$globalState.i2
v=w.t(w,y.grD())
if(v==null)return
if(y.gUU().gy8()==null)return
u=$globalState.N0!=null&&$globalState.N0.jO!==y.grD()
t=this.c
z.a=t
z.b=x
if(u){z.a=H.Gy(z.a)
z.b=H.Gy(z.b)}x=$globalState.Xz
w="receive "+H.d(t)
x.SQ
x.Rk.PN(new H.IY(v,new H.JG(z,y,u),w))}},JG:{"":"Tp;a,e,f",
call$0:function(){var z,y
z=this.e
if(z.gUU().gy8()!=null){if(this.f){y=this.a
y.a=H.Hh(y.a)
y.b=H.Hh(y.b)}y=this.a
z.gUU().CT(y.a,y.b)}}},ns:{"":"Iy;Yz<,m2,rD",
LV:function(a,b){H.ff([a,b],new H.wd(this,a,b))},
n:function(a,b){var z
if(b==null)return!1
z=J.x(b)
if(typeof b==="object"&&b!==null&&!!z.$isns)z=J.de(this.Yz,b.Yz)&&J.de(this.rD,b.rD)&&J.de(this.m2,b.m2)
else z=!1
return z},
giO:function(a){var z,y,x
z=this.Yz
if(typeof z!=="number")throw z.O()
y=this.rD
if(typeof y!=="number")throw y.O()
x=this.m2
if(typeof x!=="number")throw H.s(x)
return(z<<16^y<<8^x)>>>0},
$isns:true,
$isbC:true},wd:{"":"Tp;a,b,c",
call$0:function(){var z,y,x,w
z=this.a
y=this.c
z.yS(y)
x=H.Gy(H.Pd(["command","message","port",z,"msg",this.b,"replyTo",y]))
if($globalState.EF===!0){$globalState.vd.K3
self.postMessage(x)}else{y=$globalState.XC
w=y.t(y,z.gYz())
if(w!=null)w.postMessage(x)}}},fc:{"":"a;wY<,y8<",
CT:function(a,b){return this.y8.call$2(a,b)},
zH:function(){var z=$globalState.N0
z.mg(z,this.wY,this)},
static:{"":"b9",Ty:function(){var z=$.b9
$.b9=z+1
z=new H.fc(z,null)
z.zH()
return z}}},yc:{"":"Tp;a",
call$1:function(a){return this.a.call$0()}},I9:{"":"HU;Gx,Oj",
Pq:function(a){},
wb:function(a){var z=this.Oj
if(z.t(z,a)!=null)return
z=this.Oj
z.u(z,a,!0)
J.kH(a,new H.XT(this))},
w5:function(a){var z=this.Oj
if(z.t(z,a)!=null)return
z=this.Oj
z.u(z,a,!0)
z=a.gCP(a)
z.aN(z,new H.kY(this))},
aC:function(a){},
pC:function(a){this.aC(a.ZQ)},
j9:function(a){},
Po:function(){this.Oj=new H.fP(null)},
static:{ZF:function(){var z=new H.I9([],new H.X1())
z.Po()
return z}}},XT:{"":"Tp;a",
call$1:function(a){return this.a.hQ(a)}},kY:{"":"Tp;a",
call$1:function(a){return this.a.hQ(a)}},Bj:{"":"jP;hU,Oj",
aC:function(a){var z=J.x(a)
if(typeof a==="object"&&a!==null&&!!z.$isJM)return["sendport",$globalState.oL,a.rD,a.UU.gwY()]
if(typeof a==="object"&&a!==null&&!!z.$isns)return["sendport",a.Yz,a.rD,a.m2]
throw H.b("Illegal underlying port "+H.d(a))},
pC:function(a){var z=a.NO
return["isolateSink",this.aC(a.ZQ),z]},
j9:function(a){return["closeToken"]}},NO:{"":"oo;Oj",
aC:function(a){var z=J.x(a)
if(typeof a==="object"&&a!==null&&!!z.$isJM)return new H.JM(a.UU,a.rD)
if(typeof a==="object"&&a!==null&&!!z.$isns)return new H.ns(a.Yz,a.m2,a.rD)
throw H.b("Illegal underlying port "+H.d(a))},
pC:function(a){var z=new H.or(!1,this.aC(a.ZQ))
z.NO=a.NO
return z},
j9:function(a){return a}},II:{"":"iY;SY",
Vf:function(a){var z,y,x,w,v,u
z=J.U6(a)
y=z.t(a,1)
x=z.t(a,2)
w=z.t(a,3)
if(J.de(y,$globalState.oL)){z=$globalState.i2
v=z.t(z,x)
if(v==null)return
u=v.Zt(w)
if(u==null)return
return new H.JM(u,x)}else return new H.ns(y,w,x)},
Yf:function(a){var z,y,x
z=J.U6(a)
y=this.Vf(z.t(a,1))
x=new H.or(!1,y)
x.NO=z.t(a,2)
return x},
kv:function(a){return C.Im}},fP:{"":"a;MD",
t:function(a,b){return b.__MessageTraverser__attached_info__},
u:function(a,b,c){this.MD.push(b)
b.__MessageTraverser__attached_info__=c},
CH:function(a){this.MD=P.A(null,null)},
F4:function(){var z,y,x
for(z=this.MD.length,y=0;y<z;++y){x=this.MD
if(y>=x.length)throw H.e(y)
x[y].__MessageTraverser__attached_info__=null}this.MD=null}},X1:{"":"a;",
t:function(a,b){return},
u:function(a,b,c){},
CH:function(a){},
F4:function(){}},HU:{"":"a;",
h7:function(a){var z,y
if(H.vM(a))return this.Pq(a)
y=this.Oj
y.CH(y)
z=null
try{z=this.hQ(a)}finally{this.Oj.F4()}return z},
hQ:function(a){var z
if(a==null||typeof a==="string"||typeof a==="number"||typeof a==="boolean")return this.Pq(a)
z=J.x(a)
if(typeof a==="object"&&a!==null&&(a.constructor===Array||!!z.$isList))return this.wb(a)
if(typeof a==="object"&&a!==null&&!!z.$isT8)return this.w5(a)
if(typeof a==="object"&&a!==null&&!!z.$isbC)return this.aC(a)
if(typeof a==="object"&&a!==null&&!!z.$isor)return this.pC(a)
if(typeof a==="object"&&a!==null&&!!z.$isNU)return this.j9(a)
return this.N1(a)},
N1:function(a){throw H.b("Message serialization: Illegal value "+H.d(a)+" passed")}},oo:{"":"HU;",
Pq:function(a){return a},
wb:function(a){var z,y,x,w,v
if(typeof a!=="string"&&(typeof a!=="object"||a===null||a.constructor!==Array&&!H.wV(a,a[init.dispatchPropertyName])))return this.OD(1,a)
z=this.Oj
y=z.t(z,a)
if(y!=null)return y
x=a.length
y=P.A(x,null)
z=this.Oj
z.u(z,a,y)
for(z=y.length,w=0;w<x;++w){if(w>=a.length)throw H.e(w)
v=this.hQ(a[w])
if(w>=z)throw H.e(w)
y[w]=v}return y},
OD:function(a,b){var z,y,x,w,v,u
z=this.Oj
y=z.t(z,b)
if(y!=null)return y
z=J.U6(b)
x=z.gB(b)
y=P.A(x,null)
w=this.Oj
w.u(w,b,y)
for(w=y.length,v=0;v<x;++v){u=this.hQ(z.t(b,v))
if(v>=w)throw H.e(v)
y[v]=u}return y},
w5:function(a){var z,y
z={}
y=this.Oj
z.a=y.t(y,a)
y=z.a
if(y!=null)return y
z.a=P.L5(null,null,null,null,null)
y=this.Oj
y.u(y,a,z.a)
a.aN(a,new H.OW(z,this))
return z.a}},OW:{"":"Tp;a,b",
call$2:function(a,b){var z=this.b
J.kW(this.a.a,z.hQ(a),z.hQ(b))}},jP:{"":"HU;",
Pq:function(a){return a},
wb:function(a){var z,y,x
z=this.Oj
y=z.t(z,a)
if(y!=null)return["ref",y]
x=this.hU
this.hU=x+1
z=this.Oj
z.u(z,a,x)
return["list",x,this.i0(a)]},
w5:function(a){var z,y,x,w
z=this.Oj
y=z.t(z,a)
if(y!=null)return["ref",y]
x=this.hU
this.hU=x+1
z=this.Oj
z.u(z,a,x)
z=a.gvc()
w=this.i0(P.F(z,!0,H.W8(z,"mW",0)))
z=a.gCP(a)
return["map",x,w,this.i0(z.br(z))]},
i0:function(a){var z,y,x,w,v
if(typeof a!=="string"&&(typeof a!=="object"||a===null||a.constructor!==Array&&!H.wV(a,a[init.dispatchPropertyName])))return this.PP(1,a)
z=a.length
y=P.A(z,null)
for(x=y.length,w=0;w<z;++w){if(w>=a.length)throw H.e(w)
v=this.hQ(a[w])
if(w>=x)throw H.e(w)
y[w]=v}return y},
PP:function(a,b){var z,y,x,w,v,u
z=J.U6(b)
y=z.gB(b)
x=P.A(y,null)
for(w=x.length,v=0;v<y;++v){u=this.hQ(z.t(b,v))
if(v>=w)throw H.e(v)
x[v]=u}return x}},iY:{"":"a;",
QS:function(a){if(H.uu(a))return a
this.SY=P.Py(null,null,null,null,null)
return this.Tf(a)},
Tf:function(a){var z,y
if(a==null||typeof a==="string"||typeof a==="number"||typeof a==="boolean")return a
z=J.U6(a)
switch(z.t(a,0)){case"ref":y=z.t(a,1)
z=this.SY
return z.t(z,y)
case"list":return this.Ew(a)
case"map":return this.Q2(a)
case"sendport":return this.Vf(a)
case"isolateSink":return this.Yf(a)
case"closeToken":return this.kv(a)
default:return this.PR(a)}},
Ew:function(a){var z,y,x,w,v
z=J.U6(a)
y=z.t(a,1)
x=z.t(a,2)
if(typeof x!=="object"||x===null||(x.constructor!==Array||!!x.immutable$list)&&!H.wV(x,x[init.dispatchPropertyName]))return this.Xr(1,x,y)
z=this.SY
z.u(z,y,x)
w=x.length
for(v=0;v<w;++v){if(v>=x.length)throw H.e(v)
z=this.Tf(x[v])
if(v>=x.length)throw H.e(v)
x[v]=z}return x},
Xr:function(a,b,c){var z,y,x
z=this.SY
z.u(z,c,b)
z=J.U6(b)
y=z.gB(b)
if(typeof y!=="number")throw H.s(y)
x=0
for(;x<y;++x)z.u(b,x,this.Tf(z.t(b,x)))
return b},
Q2:function(a){var z,y,x,w,v,u,t,s,r
z=P.L5(null,null,null,null,null)
y=J.U6(a)
x=y.t(a,1)
w=this.SY
w.u(w,x,z)
v=y.t(a,2)
if(typeof v!=="string"&&(typeof v!=="object"||v===null||v.constructor!==Array&&!H.wV(v,v[init.dispatchPropertyName])))return this.Dm(1,a,z,v,y)
u=y.t(a,3)
if(typeof u!=="string"&&(typeof u!=="object"||u===null||u.constructor!==Array&&!H.wV(u,u[init.dispatchPropertyName])))return this.Dm(2,0,z,v,0,u)
t=v.length
for(s=0;s<t;++s){if(s>=v.length)throw H.e(s)
r=this.Tf(v[s])
if(s>=u.length)throw H.e(s)
z.u(z,r,this.Tf(u[s]))}return z},
Dm:function(a,b,c,d,e,f){switch(a){case 0:c=P.L5(null,null,null,null,null)
e=J.U6(b)
z=e.t(b,1)
y=this.SY
y.u(y,z,c)
d=e.t(b,2)
case 1:a=0
f=e.t(b,3)
case 2:var z,y,x,w
a=0
e=J.U6(d)
x=e.gB(d)
if(typeof x!=="number")throw H.s(x)
y=J.U6(f)
w=0
for(;w<x;++w)c.u(c,this.Tf(e.t(d,w)),this.Tf(y.t(f,w)))
return c}},
PR:function(a){throw H.b("Unexpected serialized object")}},yH:{"":"a;vw,Qg,U7?",
Qa:function(a,b){var z,y
if(a===0)z=$.jk().setTimeout==null||$globalState.EF===!0
else z=!1
if(z){this.U7=1
z=$globalState.Xz
y=$globalState.N0
z.SQ
z.Rk.PN(new H.IY(y,new H.FA(this,b),"timer"))
this.Qg=!0}else if($.jk().setTimeout!=null){z=$globalState.Xz
z.bZ=z.bZ+1
this.U7=$.jk().setTimeout(H.tR(new H.Av(this,b),0),a)}else throw H.b(new P.ub("Timer greater than 0."))},
static:{cy:function(a,b){var z=new H.yH(!0,!1,null)
z.Qa(a,b)
return z}}},FA:{"":"Tp;a,b",
call$0:function(){this.a.sU7(null)
this.b.call$0()}},Av:{"":"Tp;c,d",
call$0:function(){this.c.sU7(null)
var z=$globalState.Xz
z.bZ=z.bZ-1
this.d.call$0()}}}],["_js_helper","dart:_js_helper",,H,{wV:function(a,b){var z,y
if(b!=null){z=b.x
if(z!=null)return z}y=J.x(a)
return typeof a==="object"&&a!==null&&!!y.$isXj},d:function(a){var z
if(typeof a==="string")return a
if(typeof a==="number"){if(a!==0)return""+a}else if(!0===a)return"true"
else if(!1===a)return"false"
else if(a==null)return"null"
z=J.AG(a)
if(typeof z!=="string")throw H.b(new P.AT(a))
return z},Ql:function(a){$.te=$.te+("_"+H.d(a))
$.eb=$.eb+("_"+H.d(a))},eQ:function(a){var z=a.$identityHash
if(z==null){z=Math.random()*0x3fffffff|0
a.$identityHash=z}return z},ib:function(a){if(typeof dartPrint=="function"){dartPrint(a)
return}if(typeof console=="object"&&typeof console.log=="function"){console.log(a)
return}if(typeof window=="object")return
if(typeof print=="function"){print(a)
return}throw "Unable to print message: " + String(a)},lh:function(a){var z,y,x
z=H.xb(J.x(a))
if(J.de(z,"Object")){y=String(a.constructor).match(/^\s*function\s*(\S*)\s*\(/)[1]
if(typeof y==="string")z=y}x=J.rY(z)
if(x.j(z,0)===36)z=x.yn(z,1)
x=H.oX(a)
return H.d(z)+H.ia(x,0)},a5:function(a){return"Instance of '"+H.lh(a)+"'"},rD:function(a){var z=new Array(a)
z.fixed$length=!0
return z},VK:function(a){var z,y,x,w,v,u
z=a.length
for(y=z<=500,x="",w=0;w<z;w+=500){if(y)v=a
else{u=w+500
u=u<z?u:z
v=a.slice(w,u)}x+=String.fromCharCode.apply(null,v)}return x},Cq:function(a){var z,y,x
z=[]
for(y=new H.a7(a,a.length,0,null);y.G();){x=y.Oe
if(typeof x!=="number"||Math.floor(x)!==x)throw H.b(new P.AT(x))
if(x<=65535)z.push(x)
else if(x<=1114111){z.push(55296+(C.CD.m(x-65536,10)&1023))
z.push(56320+(x&1023))}else throw H.b(new P.AT(x))}return H.VK(z)},eT:function(a){var z,y
for(z=new H.a7(a,a.length,0,null);z.G();){y=z.Oe
if(typeof y!=="number"||Math.floor(y)!==y)throw H.b(new P.AT(y))
if(y<0)throw H.b(new P.AT(y))
if(y>65535)return H.Cq(a)}return H.VK(a)},of:function(a,b){if(a==null||typeof a==="boolean"||typeof a==="number"||typeof a==="string")throw H.b(new P.AT(a))
return a[b]},aw:function(a,b,c){if(a==null||typeof a==="boolean"||typeof a==="number"||typeof a==="string")throw H.b(new P.AT(a))
a[b]=c},s:function(a){throw H.b(new P.AT(a))},e:function(a){if(typeof a!=="number"||Math.floor(a)!==a)H.s(a)
throw H.b(new P.bJ("value "+H.d(a)))},b:function(a){var z
if(a==null)a=new P.LK()
z=new Error()
z.dartException=a
if("defineProperty" in Object){Object.defineProperty(z, "message", { get: H.Eu.call$0 })
z.name=""}else z.toString=H.Eu.call$0
return z},Ju:function(){return J.AG(this.dartException)},vh:function(a){throw H.b(a)},Ru:function(a){var z,y,x,w,v,u,t,s,r,q,p,o,n,m
z=new H.Am(a)
if(a==null)return
if(typeof a!=="object")return a
if("dartException" in a)return z.call$1(a.dartException)
else if(!("message" in a))return a
y=a.message
if("number" in a&&typeof a.number=="number"){x=a.number
w=x&65535
if((C.jn.m(x,16)&8191)===10)switch(w){case 438:return z.call$1(H.T3(H.d(y)+" (Error "+w+")",null))
case 445:case 5007:v=H.d(y)+" (Error "+w+")"
return z.call$1(new H.ZQ(v,null))
default:}}if(a instanceof TypeError){v=$.WD()
u=$.OI()
t=$.PH()
s=$.D1()
r=$.rx()
q=$.Kr()
p=$.zO()
$.PB()
o=$.eA()
n=$.ko()
m=v.qS(y)
if(m!=null)return z.call$1(H.T3(y,m))
else{m=u.qS(y)
if(m!=null){m.method="call"
return z.call$1(H.T3(y,m))}else{m=t.qS(y)
if(m==null){m=s.qS(y)
if(m==null){m=r.qS(y)
if(m==null){m=q.qS(y)
if(m==null){m=p.qS(y)
if(m==null){m=s.qS(y)
if(m==null){m=o.qS(y)
if(m==null){m=n.qS(y)
v=m!=null}else v=!0}else v=!0}else v=!0}else v=!0}else v=!0}else v=!0}else v=!0
if(v){v=m==null?null:m.method
return z.call$1(new H.ZQ(y,v))}}}v=typeof y==="string"?y:""
return z.call$1(new H.vV(v))}if(a instanceof RangeError){if(typeof y==="string"&&y.indexOf("call stack")!==-1)return new P.VS()
return z.call$1(new P.AT(null))}if(typeof InternalError=="function"&&a instanceof InternalError)if(typeof y==="string"&&y==="too much recursion")return new P.VS()
return a},Pd:function(a){var z,y,x
z=J.GP(a)
y=P.L5(null,null,null,null,null)
for(;z.G();){x=z.gl()
z.G()
y.u(y,x,z.gl())}return y},ft:function(a,b,c,d,e){var z=J.x(c)
if(z.n(c,0))return H.zd(b,new H.dr(a))
else if(z.n(c,1))return H.zd(b,new H.TL(a,d))
else if(z.n(c,2))return H.zd(b,new H.KX(a,d,e))
else throw H.b(new P.HG("Unsupported number of arguments for wrapped closure"))},tR:function(a,b){var z
if(a==null)return
z=a.$identity
if(!!z)return z
z=(function ($2, $3) { return function($0, $1) { return $3(a, $2, b, $0, $1) }})($globalState.N0, H.eH.call$5)
a.$identity=z
return z},ag:function(a){throw H.b(new P.t7("Cyclic initialization for static "+H.d(a)))},VM:function(a,b){if(a!=null)a.$builtinTypeInfo=b
return a},oX:function(a){if(a==null)return
return a.$builtinTypeInfo},IM:function(a,b){return H.Y9(a["$as"+H.d(b)],H.oX(a))},W8:function(a,b,c){var z=H.IM(a,b)
return z==null?null:z[c]},Ko:function(a){if(a==null)return"dynamic"
else if(typeof a==="object"&&a!==null&&a.constructor===Array)return a[0].builtin$cls+H.ia(a,1)
else if(typeof a=="function")return a.builtin$cls
else return},ia:function(a,b){var z,y,x,w,v,u
if(a==null)return""
z=P.p9("")
for(y=b,x=!0,w=!0;y<a.length;++y){if(x)x=!1
else z.v9=z.v9+", "
v=a[y]
if(v!=null)w=!1
u=H.Ko(v)
u=typeof u==="string"?u:u
z.v9=z.v9+u}return w?"":"<"+H.d(z)+">"},Y9:function(a,b){if(typeof a==="object"&&a!==null&&a.constructor===Array)b=a
else if(typeof a=="function"){a=H.ml(a,null,b)
if(typeof a==="object"&&a!==null&&a.constructor===Array)b=a
else if(typeof a=="function")b=H.ml(a,null,b)}return b},ml:function(a,b,c){return a.apply(b,c)},Ph:function(a){return a.constructor.name},f4:function(a){return H.xb(a)},vK:function(a){return H.xb(a)},mv:function(a){var z=H.xb(a)
if(z==="BeforeUnloadEvent")return"Event"
if(z==="DataTransfer")return"Clipboard"
if(z==="GeoGeolocation")return"Geolocation"
if(z==="WorkerMessageEvent")return"MessageEvent"
if(z==="XMLDocument")return"Document"
return z},Tx:function(a){var z=H.xb(a)
if(z==="Document"){if(!!a.xmlVersion)return"Document"
return"HTMLDocument"}if(z==="BeforeUnloadEvent")return"Event"
if(z==="DataTransfer")return"Clipboard"
if(z==="HTMLDDElement")return"HTMLElement"
if(z==="HTMLDTElement")return"HTMLElement"
if(z==="HTMLPhraseElement")return"HTMLElement"
if(z==="Position")return"Geoposition"
if(z==="Object")if(window.DataView&&a instanceof window.DataView)return"DataView"
return z},xb:function(a){var z,y,x,w
if(a==null)return"Null"
z=a.constructor
if(typeof z==="function"){y=z.builtin$cls
if(y!=null)return y
y=z.name
if(typeof y==="string")x=y!==""&&y!=="Object"&&y!=="Function.prototype"
else x=!1
if(x)return y}w=Object.prototype.toString.call(a)
return w.substring(8,w.length-1)},YE:function(a,b){if(!!/^HTML[A-Z].*Element$/.test(b)){if(Object.prototype.toString.call(a)==="[object Object]")return
return"HTMLElement"}return},VP:function(){var z=H.IG()
if(typeof dartExperimentalFixupGetTag=="function")return H.I8(dartExperimentalFixupGetTag,z)
return z},IG:function(){if(typeof navigator!=="object")return H.qA
var z=navigator.userAgent
if(z.indexOf("Chrome")!==-1||z.indexOf("DumpRenderTree")!==-1)return H.qA
else if(z.indexOf("Firefox")!==-1)return H.Bi
else if(z.indexOf("Trident/")!==-1)return H.tu
else if(z.indexOf("Opera")!==-1)return H.D3
else if(z.indexOf("AppleWebKit")!==-1)return H.nY
else return H.DA},I8:function(a,b){return new H.Vs(a((function(invoke, closure){return function(arg){ return invoke(closure, arg); };})(H.dq.call$2, b)))},jm:function(a,b){return a.call$1(b)},F3:function(a){return"Instance of "+$.nn().call$1(a)},wz:function(a){return H.eQ(a)},iw:function(a,b,c){Object.defineProperty(a, b, {value: c, enumerable: false, writable: true, configurable: true})},VQ:function(a,b){H.d4(a,b,!0)},MT:function(a,b){H.d4(a,b,!1)},XJ:function(a,b,c){var z,y,x
if($.LI==null)$.LI=[]
z=c
for(y=z.length,x=0;x<y;++x){$.LI.push(z[x])
$.LI.push(a)}H.d4(a,b,!1)},d4:function(a,b,c){var z,y,x,w
z=b.prototype
if($.NP==null)$.NP={}
if($.kP==null)$.kP={}
y=a.split("|")
for(x=0;x<y.length;++x){w=y[x]
$.NP[w]=z
$.kP[w]=c}},Yz:function(){},JC:function(a,b){var z=$.NP
if(z==null)return
return a.call(z,b)?z[b]:null},Px:function(a){var z,y,x,w,v
z=Object.prototype.hasOwnProperty
y=$.nn().call$1(a)
x=H.JC(z,y)
if(x==null){w=H.YE(a,y)
if(w!=null)x=H.JC(z,w)}if(x==null)return
v=$.kP
if(v!=null&&v[y]===true)return H.Va(x)
else return J.Qu(x,Object.getPrototypeOf(a),null,null)},Va:function(a){return J.Qu(a,!1,null,!!a.$isXj)},Zr:{"":"a;hO,Vp,vJ,pp,pz,Az",
qS:function(a){var z,y,x
z=new RegExp(this.hO).exec(a)
if(z==null)return
y={}
x=this.Vp
if(x!==-1)y.arguments=z[x+1]
x=this.vJ
if(x!==-1)y.argumentsExpr=z[x+1]
x=this.pp
if(x!==-1)y.expr=z[x+1]
x=this.pz
if(x!==-1)y.method=z[x+1]
x=this.Az
if(x!==-1)y.receiver=z[x+1]
return y},
static:{"":"lm,k1,Re,fN,qi,rZ,BX,tt,dt,A7",cM:function(a){var z,y,x,w,v,u
a=a.replace(String({}), '$receiver$').replace(new RegExp("[[\\]{}()*+?.\\\\^$|]",'g'),'\\$&')
z=a.match(/\\\$[a-zA-Z]+\\\$/g)
if(z==null)z=[]
y=z.indexOf("\\$arguments\\$")
x=z.indexOf("\\$argumentsExpr\\$")
w=z.indexOf("\\$expr\\$")
v=z.indexOf("\\$method\\$")
u=z.indexOf("\\$receiver\\$")
return new H.Zr(a.replace('\\$arguments\\$','((?:x|[^x])*)').replace('\\$argumentsExpr\\$','((?:x|[^x])*)').replace('\\$expr\\$','((?:x|[^x])*)').replace('\\$method\\$','((?:x|[^x])*)').replace('\\$receiver\\$','((?:x|[^x])*)'),y,x,w,v,u)},S7:function(a){return function($expr$) {
  var $argumentsExpr$ = '$arguments$'
  try {
    $expr$.$method$($argumentsExpr$);
  } catch (e) {
    return e.message;
  }
}(a)},pb:function(){return function() {
  var $argumentsExpr$ = '$arguments$'
  try {
    null.$method$($argumentsExpr$);
  } catch (e) {
    return e.message;
  }
}()},u9:function(){return function() {
  var $argumentsExpr$ = '$arguments$'
  try {
    (void 0).$method$($argumentsExpr$);
  } catch (e) {
    return e.message;
  }
}()},Mj:function(a){return function($expr$) {
  try {
    $expr$.$method$;
  } catch (e) {
    return e.message;
  }
}(a)},Qd:function(){return function() {
  try {
    null.$method$;
  } catch (e) {
    return e.message;
  }
}()},m0:function(){return function() {
  try {
    (void 0).$method$;
  } catch (e) {
    return e.message;
  }
}()}}},ZQ:{"":"Ge;UQ,pz",
bu:function(a){var z=this.pz
if(z==null)return"NullError: "+H.d(this.UQ)
return"NullError: Cannot call \""+H.d(z)+"\" on null"},
$isGe:true},az:{"":"Ge;UQ,pz,Az",
bu:function(a){var z,y
z=this.pz
if(z==null)return"NoSuchMethodError: "+H.d(this.UQ)
y=this.Az
if(y==null)return"NoSuchMethodError: Cannot call \""+z+"\" ("+H.d(this.UQ)+")"
return"NoSuchMethodError: Cannot call \""+z+"\" on \""+y+"\" ("+H.d(this.UQ)+")"},
$isGe:true,
static:{T3:function(a,b){var z,y
z=b==null
y=z?null:b.method
z=z?null:b.receiver
return new H.az(a,y,z)}}},vV:{"":"Ge;UQ",
bu:function(a){var z=this.UQ
return C.xB.gl0(z)?"Error":"Error: "+z}},Am:{"":"Tp;a",
call$1:function(a){var z=J.x(a)
if(typeof a==="object"&&a!==null&&!!z.$isGe)if(a.$thrownJsError==null)a.$thrownJsError=this.a
return a}},XO:{"":"a;Wu,Qj",
bu:function(a){var z,y
z=this.Qj
if(z!=null)return z
z=this.Wu
y=typeof z==="object"?z.stack:null
z=y==null?"":y
this.Qj=z
return z}},dr:{"":"Tp;a",
call$0:function(){return this.a.call$0()}},TL:{"":"Tp;b,c",
call$0:function(){return this.b.call$1(this.c)}},KX:{"":"Tp;d,e,f",
call$0:function(){return this.d.call$2(this.e,this.f)}},Tp:{"":"a;",
bu:function(a){return"Closure"}},v:{"":"Tp;nq,Tu,Az",
n:function(a,b){var z
if(b==null)return!1
if(this===b)return!0
z=J.x(b)
if(typeof b!=="object"||b===null||!z.$isv)return!1
return this.nq===b.nq&&this.Tu===b.Tu&&this.Az===b.Az},
giO:function(a){return J.v1(this.nq)+J.v1(this.Tu)+J.v1(this.Az)&0x3ffffff},
$isv:true},cu:{"":"a;rv,wi",
bu:function(a){var z,y,x
z=this.wi
if(z!=null)return z
y=this.rv
x=H.Jg(y)
y=x==null?y:x
this.wi=y
return y},
giO:function(a){return J.v1(this.rv)},
n:function(a,b){var z
if(b==null)return!1
z=J.x(b)
return typeof b==="object"&&b!==null&&!!z.$iscu&&J.de(this.rv,b.rv)},
$iscu:true},Vs:{"":"Tp;a",
call$1:function(a){return this.a(a)}}}],["dart._collection.dev","dart:_collection-dev",,H,{Zi:function(a,b,c,d,e){var z,y,x,w,v,u
if(typeof c!=="object"||c===null||(c.constructor!==Array||!!c.immutable$list)&&!H.wV(c,c[init.dispatchPropertyName]))return H.lC(1,a,b,c,d,e)
if(b<d)for(z=b+e-1,y=d+e-1,x=a.length,w=c.length;z>=b;--z,--y){if(z<0||z>=x)throw H.e(z)
v=a[z]
if(y<0||y>=w)throw H.e(y)
c[y]=v}else for(x=b+e,w=a.length,v=c.length,y=d,z=b;z<x;++z,++y){if(z<0||z>=w)throw H.e(z)
u=a[z]
if(y<0||y>=v)throw H.e(y)
c[y]=u}},lC:function(a,b,c,d,e,f){var z,y,x
if(c<e)for(z=c+f-1,y=e+f-1;z>=c;--z,--y){if(z<0||z>=b.length)throw H.e(z)
C.Nm.u(d,y,b[z])}else for(x=c+f,y=e,z=c;z<x;++z,++y){if(z<0||z>=b.length)throw H.e(z)
C.Nm.u(d,y,b[z])}},bQ:function(a,b){var z
for(z=new H.a7(a,a.length,0,null);z.G();)b.call$1(z.Oe)},mx:function(a,b,c){var z,y,x
for(y=0;y<$.RM().length;++y){x=$.RM()
if(y>=x.length)throw H.e(y)
if(x[y]===a)return H.d(b)+"..."+H.d(c)}z=P.p9("")
try{$.RM().push(a)
z.KF(b)
z.We(a,", ")
z.KF(c)}finally{x=$.RM()
if(0>=x.length)throw H.e(0)
x.pop()}return z.gv9()},S6:function(a,b,c){var z
if(b<0||b>a.length){z=a.length
throw H.b(new P.bJ("value "+b+" not in range 0.."+z))}if(c<b||c>a.length){z=a.length
throw H.b(new P.bJ("value "+c+" not in range "+b+".."+z))}},qG:function(a,b,c,d,e){var z
H.S6(a,b,c)
z=c-b
if(z===0)return
if(e<0)throw H.b(new P.AT(e))
if(e+z>d.length)throw H.b(new P.lj("Not enough elements"))
H.Zi(d,e,a,b,z)},a7:{"":"a;pN,wh,Mm,Oe",
gl:function(){return this.Oe},
G:function(){var z,y,x,w
z=this.pN
y=J.U6(z)
x=y.gB(z)
if(this.wh!==x)throw H.b(new P.UV(z))
w=this.Mm
if(w>=x){this.Oe=null
return!1}this.Oe=y.Zv(z,w)
this.Mm=this.Mm+1
return!0}},i1:{"":"mW;pN,Yd",
gA:function(a){var z=this.pN
z=z.gA(z)
z=new H.MH(null,z,this.Yd)
H.VM(z,[H.W8(this,"i1",0),H.W8(this,"i1",1)])
return z},
gB:function(a){var z=this.pN
return z.gB(z)},
$asmW:function(a,b){return[b]}},MH:{"":"AC;Oe,Vc,Yd",
lU:function(a){return this.Yd.call$1(a)},
G:function(){var z=this.Vc
if(z.G()){this.Oe=this.lU(z.gl())
return!0}this.Oe=null
return!1},
gl:function(){return this.Oe},
$asAC:function(a,b){return[b]}},SU:{"":"a;"}}],["dart._js_names","dart:_js_names",,H,{Jg:function(a){return init.mangledGlobalNames[a]}}],["dart.async","dart:async",,P,{uh:function(a,b){var z
if(a==null||typeof a==="boolean"||typeof a==="number"||typeof a==="string")return
z=$.ij()
z.u(z,a,b)},XS:function(a){var z
if(a==null||typeof a==="boolean"||typeof a==="number"||typeof a==="string")return
z=$.ij()
return z.t(z,a)},BG:function(){var z,y,x,w
for(;y=$.P8(),y.JV!==y.D8;){z=$.P8().Ux()
try{z.call$0()}catch(x){H.Ru(x)
w=C.CD.Z(C.RT.vT,1000)
H.cy(w<0?0:w,P.qZ)
throw x}}$.TH=!1},IA:function(a){$.P8().PN(a)
if(!$.TH){P.jL(C.RT,P.qZ)
$.TH=!0}},Vd:function(a){var z=$.o8()
z.J0(a,z)},pH:function(a){var z,y,x,w,v,u,t,s,r
z={}
z.a=null
z.b=null
y=new P.VN(z)
z.c=0
for(x=new H.a7(a,a.length,0,null);x.G();){w=x.Oe
v=z.c
z.c=v+1
u=w.OA(y)
t=new P.vs(0,$.o8(),null,null,new P.iK(z,v),null,null,null)
t.$builtinTypeInfo=[null]
s=t.IF
s.Tl=s.Tl+1
u.kj(t)}y=z.c
if(y===0)return P.Ab(C.xD,null)
z.b=P.A(y,null)
y=J.Q
r=new P.Zf(P.Dt(y))
H.VM(r,[y])
z.a=r
return z.a.MM},qK:function(a,b){if(b==null)return a
if(P.XS(a)!=null)return a
P.uh(a,b)
return a},FE:function(a,b,c){var z,y,x,w
try{b.call$1(a.call$0())}catch(x){w=H.Ru(x)
z=w
y=new H.XO(x,null)
c.call$1(P.qK(z,y))}},NX:function(a,b){return new P.dR(a,b)},jL:function(a,b){var z=C.CD.Z(a.vT,1000)
return H.cy(z<0?0:z,b)},VN:{"":"Tp;a",
call$1:function(a){var z=this.a
if(z.b!=null){z.b=null
z=z.a
z.w0
z=z.MM
if(z.tj!==0)H.vh(new P.lj("Future already completed"))
z.iY(a,null)}}},iK:{"":"Tp;a,b",
call$1:function(a){var z,y,x
z=this.a
y=z.b
if(y==null)return
x=this.b
if(x<0||x>=y.length)throw H.e(x)
y[x]=a
z.c=z.c-1
if(z.c===0){y=z.a
z=z.b
y.aM
y=y.MM
if(y.tj!==0)H.vh(new P.lj("Future already completed"))
y.EE(z)}}},Pf:{"":"a;"},Zf:{"":"Pf;MM",$asPf:null},vs:{"":"a;tj,IF<,lQ,GR@,PM,Yx,xA,BL",
glO:function(){return this.tj>=4},
gul:function(){return this.tj===8},
gDY:function(){return this.tj===2?null:this.PM},
PL:function(a){return this.gDY().call$1(a)},
ghH:function(){return this.tj===2?null:this.xA},
QZ:function(a){return this.ghH().call$1(a)},
Rx:function(a,b){var z,y
z=new P.vs(0,$.o8(),null,null,a,null,b,null)
z.$builtinTypeInfo=[null]
y=z.IF
y.Tl=y.Tl+1
this.kj(z)
return z},
ml:function(a){return this.Rx(a,null)},
co:function(a,b){var z,y
z=new P.vs(0,$.o8(),null,null,null,b,a,null)
z.$builtinTypeInfo=[null]
y=z.IF
y.Tl=y.Tl+1
this.kj(z)
return z},
OA:function(a){return this.co(a,null)},
gdE:function(){return this.lQ},
gYG:function(){return this.lQ},
Up:function(a){this.tj=4
this.lQ=a},
EI:function(a){this.tj=8
this.lQ=a},
kj:function(a){if(this.tj>=4)P.Vd(new P.da(this,a))
else{a.GR=this.lQ
this.lQ=a}},
Rw:function(){var z,y,x
z=this.lQ
this.lQ=null
for(y=null;z!=null;y=z,z=x){x=z.gGR()
z.sGR(y)}return y},
bs:function(a){var z,y
z=J.x(a)
if(typeof a==="object"&&a!==null&&!!z.$isb8){P.GZ(a,this)
return}y=this.Rw()
this.Up(a)
P.HZ(this,y)},
kM:function(a,b){var z
if(b!=null)P.uh(a,b)
z=this.tj===2?null:this.Rw()
this.EI(a)
P.HZ(this,z)},
vs:function(a){return this.kM(a,null)},
gCD:function(){return new P.Br(this,"kM",null)},
EE:function(a){var z=J.x(a)
if(typeof a==="object"&&a!==null&&!!z.$isb8)z=!z.$isvs||a.tj<4
else z=!1
if(z){this.bs(a)
return}if(this.tj!==0)H.vh(new P.lj("Future already completed"))
this.tj=1
P.Vd(new P.rH(this,a))},
iY:function(a,b){if(this.tj!==0)H.vh(new P.lj("Future already completed"))
this.tj=1
P.Vd(new P.ZL(this,a,b))},
B0:function(a,b){this.EE(a)},
$isvs:true,
$isb8:true,
static:{"":"ew,Ry,C3,oN,NK",Dt:function(a){var z=new P.vs(0,$.o8(),null,null,null,null,null,null)
H.VM(z,[a])
return z},Ab:function(a,b){var z=new P.vs(0,$.o8(),null,null,null,null,null,null)
H.VM(z,[b])
z.B0(a,b)
return z},GZ:function(a,b){b.tj=2
if(!!a.$isvs)if(a.tj>=4)P.HZ(a,b)
else a.kj(b)
else a.Rx(new P.xw(b),new P.dm(b))},yE:function(a,b){var z
do{z=b.gGR()
b.sGR(null)
P.HZ(a,b)
if(z!=null){b=z
continue}else break}while(!0)},HZ:function(a,b){var z,y,x,w,v,u,t,s
z={}
z.e=a
for(;!0;){y={}
if(!z.e.glO())return
x=z.e.gul()
if(x&&b==null){y=z.e
y.gIF().ai(y.gYG())
return}if(b==null)return
if(b.GR!=null){P.yE(z.e,b)
return}if(x){w=z.e.gIF()
v=b.IF
v=w.gAy()!==v.gAy()
w=v}else w=!1
if(w){y=z.e
y.gIF().ai(y.gYG())
return}w=$.o8()
v=b.IF
if(w!==v){v.Jg(new P.mi(z,b),!1)
return}y.b=null
y.c=null
y.d=!1
v.Tl=v.Tl-1
v.Jg(new P.jb(z,y,x,b),!1)
if(y.d===!0)return
w=y.b===!0
if(w){v=y.c
u=J.x(v)
u=typeof v==="object"&&v!==null&&!!u.$isb8
v=u}else v=!1
if(v){t=y.c
y=J.x(t)
if(typeof t==="object"&&t!==null&&!!y.$isvs&&t.tj>=4){b.tj=2
z.e=t
continue}P.GZ(t,b)
return}if(w){s=b.Rw()
y=y.c
b.tj=4
b.lQ=y}else{s=b.Rw()
y=y.c
b.tj=8
b.lQ=y}z.e=b
b=s}}}},da:{"":"Tp;a,b",
call$0:function(){P.HZ(this.a,this.b)}},xw:{"":"Tp;a",
call$1:function(a){this.a.bs(a)}},dm:{"":"Tp;b",
call$1:function(a){this.b.vs(a)}},rH:{"":"Tp;a,b",
call$0:function(){this.a.bs(this.b)}},ZL:{"":"Tp;a,b,c",
call$0:function(){this.a.kM(this.b,this.c)}},mi:{"":"Tp;c,d",
call$0:function(){P.HZ(this.c.e,this.d)}},jb:{"":"Tp;c,b,e,f",
call$0:function(){var z,y,x,w,v,u,t,s,r,q
try{t=this.c
if(!this.e){z=t.e.gdE()
t=this.f
s=t.tj===2?null:t.PM
r=this.b
if(s!=null){r.c=t.PL(z)
r.b=!0}else{r.c=z
r.b=!0}}else{y=t.e.gYG()
t=this.f
x=t.tj===2?null:t.Yx
w=!0
if(x!=null)w=x.call$1(y)
if(w===!0)s=(t.tj===2?null:t.xA)!=null
else s=!1
r=this.b
if(s){r.c=t.QZ(y)
r.b=!0}else{r.c=y
r.b=!1}}t=this.f
if(t.tj===2);}catch(q){t=H.Ru(q)
v=t
u=new H.XO(q,null)
t=this.b
t.c=P.qK(v,u)
t.b=!1}t=this.b
if(t.b===!0){t=t.c
s=J.x(t)
s=typeof t==="object"&&t!==null&&!!s.$isb8
t=s}else t=!1
if(t){t=this.f.IF
t.Tl=t.Tl+1}}},wB:{"":"Tp;c,g",
call$1:function(a){P.HZ(this.c.e,this.g)}},Gv:{"":"Tp;a,h",
call$1:function(a){var z,y,x
z=this.a
y=z.a
x=J.x(y)
if(typeof y!=="object"||y===null||!x.$isvs){z.a=P.Dt(null)
z.a.EI(a)}P.HZ(z.a,this.h)}},qh:{"":"a;",
aN:function(a,b){var z,y
z={}
y=P.Dt(null)
z.a=null
z.a=this.X5(new P.lz(z,this,b,y),!0,new P.M4(y),y.gCD())
return y},
gB:function(a){var z,y
z={}
y=new P.vs(0,$.o8(),null,null,null,null,null,null)
y.$builtinTypeInfo=[J.im]
z.a=0
this.X5(new P.B5(z),!0,new P.PI(z,y),y.gCD())
return y},
br:function(a){var z,y
z=[]
y=P.Dt([J.Q,H.W8(this,"qh",0)])
this.X5(new P.VV(this,z),!0,new P.Dy(z,y),y.gCD())
return y}},lz:{"":"Tp;a,b,c,d",
call$1:function(a){P.FE(new P.Rl(this.c,a),new P.Jb(),P.NX(this.a.a,this.d))}},Rl:{"":"Tp;e,f",
call$0:function(){return this.e.call$1(this.f)}},Jb:{"":"Tp;",
call$1:function(a){}},M4:{"":"Tp;g",
call$0:function(){this.g.bs(null)}},B5:{"":"Tp;a",
call$1:function(a){var z=this.a
z.a=z.a+1}},PI:{"":"Tp;a,b",
call$0:function(){this.b.bs(this.a.a)}},VV:{"":"Tp;a,b",
call$1:function(a){this.b.push(a)}},Dy:{"":"Tp;c,d",
call$0:function(){this.d.bs(this.c)}},MO:{"":"a;"},rE:{"":"a;"},dR:{"":"Tp;a,b",
call$1:function(a){this.a.Gv()
this.b.vs(a)}},n7:{"":"a;",
gAy:function(){return this.j0.gAy()},
ai:function(a){this.j0.ai(a)},
Kt:function(){if(!this.eU&&this.Tl===0&&this.VQ===0);},
Jg:function(a,b){var z,y,x,w,v,u
if($.o8()===this&&b!==!0&&this.eU)return a.call$0()
z=$.o8()
$.kx=this
y=this.eU
this.eU=!0
try{try{v=a.call$0()
return v}catch(u){v=H.Ru(u)
x=v
w=new H.XO(u,null)
if(b===!0)this.ai(P.qK(x,w))
else throw u}}finally{this.eU=y
$.kx=z
this.Kt()}},
J0:function(a,b){return this.j0.J0(a,b)}},Ec:{"":"n7;j0,VQ,Tl,eU",
gAy:function(){return this},
ai:function(a){var z
$.P8().PN(new P.dZ(a))
if(!$.TH){z=C.CD.Z(C.RT.vT,1000)
H.cy(z<0?0:z,P.qZ)
$.TH=!0}},
J0:function(a,b){if(this===b){P.IA(a)
return}b.Tl=b.Tl+1
P.IA(new P.Eb(a,b))}},dZ:{"":"Tp;a",
call$0:function(){var z,y
z=this.a
H.ib("Uncaught Error: "+H.d(z))
y=P.XS(z)
P.uh(z,null)
if(y!=null)H.ib("Stack Trace:\n"+H.d(y)+"\n")
throw H.b(z)}},Eb:{"":"Tp;a,b",
call$0:function(){var z=this.b
z.Tl=z.Tl-1
z.Jg(this.a,!0)}},qu:{"":"a;IF<,Zr,dD",
q6:function(){var z=this.IF
z.Tl=z.Tl-1
z.Jg(this.Zr,!0)},
gRR:function(){return new P.EV(this,"q6",null)}}}],["dart.collection","dart:collection",,P,{Ou:function(a,b){return J.de(a,b)},T9:function(a){return J.v1(a)},Py:function(a,b,c,d,e){var z=new P.k6(0,null,null,null,null)
H.VM(z,[d,e])
return z},L5:function(a,b,c,d,e){var z=new P.YB(0,null,null,null,null,null,0)
H.VM(z,[d,e])
return z},vW:function(a){var z,y,x,w
z={}
for(x=0;x<$.tw().length;++x){w=$.tw()
if(x>=w.length)throw H.e(x)
if(w[x]===a)return"{...}"}y=P.p9("")
try{$.tw().push(a)
y.KF("{")
z.a=!0
J.kH(a,new P.W0(z,y))
y.KF("}")}finally{z=$.tw()
if(0>=z.length)throw H.e(0)
z.pop()}return y.gv9()},k6:{"":"a;iI,BM,uG,LK,Mk",
gB:function(a){return this.iI},
gvc:function(){var z=new P.fG(this)
H.VM(z,[H.W8(this,"k6",0)])
return z},
gCP:function(a){var z,y
z=new P.fG(this)
H.VM(z,[H.W8(this,"k6",0)])
y=new H.i1(z,new P.oi(this))
H.VM(y,[H.W8(z,"mW",0),null])
return y},
t:function(a,b){var z,y,x,w,v,u,t
if(typeof b==="string"&&b!=="__proto__"){z=this.BM
if(z==null)y=null
else{x=z[b]
y=x===z?null:x}return y}else if(typeof b==="number"&&(b&0x3ffffff)===b){w=this.uG
if(w==null)y=null
else{x=w[b]
y=x===w?null:x}return y}else{v=this.LK
if(v==null)return
u=v[this.dR(b)]
t=this.qo(u,b)
return t<0?null:u[t+1]}},
u:function(a,b,c){var z,y,x,w,v,u,t,s
if(typeof b==="string"&&b!=="__proto__"){z=this.BM
if(z==null){y=Object.create(null)
if(y==null)y["<non-identifier-key>"]=y
else y["<non-identifier-key>"]=y
delete y["<non-identifier-key>"]
this.BM=y
z=y}if(z[b]==null){this.iI=this.iI+1
this.Mk=null}if(c==null)z[b]=z
else z[b]=c}else if(typeof b==="number"&&(b&0x3ffffff)===b){x=this.uG
if(x==null){y=Object.create(null)
if(y==null)y["<non-identifier-key>"]=y
else y["<non-identifier-key>"]=y
delete y["<non-identifier-key>"]
this.uG=y
x=y}if(x[b]==null){this.iI=this.iI+1
this.Mk=null}if(c==null)x[b]=x
else x[b]=c}else{w=this.LK
if(w==null){y=Object.create(null)
if(y==null)y["<non-identifier-key>"]=y
else y["<non-identifier-key>"]=y
delete y["<non-identifier-key>"]
this.LK=y
w=y}v=this.dR(b)
u=w[v]
if(u==null){t=[b,c]
if(t==null)w[v]=w
else w[v]=t
this.iI=this.iI+1
this.Mk=null}else{s=this.qo(u,b)
if(s>=0)u[s+1]=c
else{u.push(b,c)
this.iI=this.iI+1
this.Mk=null}}}},
aN:function(a,b){var z,y,x,w
z=this.mB()
for(y=z.length,x=0;x<y;++x){w=z[x]
b.call$2(w,this.t(this,w))
if(z!==this.Mk)throw H.b(new P.UV(this))}},
mB:function(){var z,y,x,w,v,u,t,s,r,q,p,o
z=this.Mk
if(z!=null)return z
y=P.A(this.iI,null)
x=this.BM
if(x!=null){w=Object.getOwnPropertyNames(x)
v=w.length
for(u=0,t=0;t<v;++t){y[u]=w[t];++u}}else u=0
s=this.uG
if(s!=null){w=Object.getOwnPropertyNames(s)
v=w.length
for(t=0;t<v;++t){y[u]=+w[t];++u}}r=this.LK
if(r!=null){w=Object.getOwnPropertyNames(r)
v=w.length
for(t=0;t<v;++t){q=r[w[t]]
p=q.length
for(o=0;o<p;o+=2){y[u]=q[o];++u}}}this.Mk=y
return y},
dR:function(a){return J.v1(a)&0x3ffffff},
qo:function(a,b){var z,y
if(a==null)return-1
z=a.length
for(y=0;y<z;y+=2)if(J.de(a[y],b))return y
return-1},
$isT8:true},oi:{"":"Tp;a",
call$1:function(a){return J.UQ(this.a,a)}},fG:{"":"mW;rF",
gB:function(a){return this.rF.iI},
gA:function(a){var z=this.rF
return new P.EQ(z,z.mB(),0,null)},
aN:function(a,b){var z,y,x,w
z=this.rF
y=z.mB()
for(x=y.length,w=0;w<x;++w){b.call$1(y[w])
if(y!==z.Mk)throw H.b(new P.UV(z))}},
$asmW:null},EQ:{"":"a;rF,Mk,rV,QH",
gl:function(){return this.QH},
G:function(){var z,y,x
z=this.Mk
y=this.rV
x=this.rF
if(z!==x.Mk)throw H.b(new P.UV(x))
else if(y>=z.length){this.QH=null
return!1}else{this.QH=z[y]
this.rV=y+1
return!0}}},YB:{"":"a;iI,BM,uG,LK,rP,Jr,qs",
gB:function(a){return this.iI},
gvc:function(){var z=new P.i5(this)
H.VM(z,[H.W8(this,"YB",0)])
return z},
gCP:function(a){var z,y
z=new P.i5(this)
H.VM(z,[H.W8(this,"YB",0)])
y=new H.i1(z,new P.a1(this))
H.VM(y,[H.W8(z,"mW",0),null])
return y},
x4:function(a){var z,y
if((a&0x3ffffff)===a){z=this.uG
if(z==null)return!1
return z[a]!=null}else{y=this.LK
if(y==null)return!1
return this.qo(y[this.dR(a)],a)>=0}},
t:function(a,b){var z,y,x,w,v,u
if(typeof b==="string"&&b!=="__proto__"){z=this.BM
if(z==null)return
y=z[b]
return y==null?null:y.gx0()}else if(typeof b==="number"&&(b&0x3ffffff)===b){x=this.uG
if(x==null)return
y=x[b]
return y==null?null:y.gx0()}else{w=this.LK
if(w==null)return
v=w[this.dR(b)]
u=this.qo(v,b)
if(u<0)return
return v[u].gx0()}},
u:function(a,b,c){var z,y,x,w,v,u,t,s
if(typeof b==="string"&&b!=="__proto__"){z=this.BM
if(z==null){y=Object.create(null)
y["<non-identifier-key>"]=y
delete y["<non-identifier-key>"]
this.BM=y
z=y}x=z[b]
if(x==null)z[b]=this.tS(b,c)
else x.sx0(c)}else if(typeof b==="number"&&(b&0x3ffffff)===b){w=this.uG
if(w==null){y=Object.create(null)
y["<non-identifier-key>"]=y
delete y["<non-identifier-key>"]
this.uG=y
w=y}x=w[b]
if(x==null)w[b]=this.tS(b,c)
else x.sx0(c)}else{v=this.LK
if(v==null){y=Object.create(null)
y["<non-identifier-key>"]=y
delete y["<non-identifier-key>"]
this.LK=y
v=y}u=this.dR(b)
t=v[u]
if(t==null)v[u]=[this.tS(b,c)]
else{s=this.qo(t,b)
if(s>=0)t[s].sx0(c)
else t.push(this.tS(b,c))}}},
Rz:function(a,b){var z,y,x,w
if(typeof b==="string"&&b!=="__proto__")return this.yj(this.BM,b)
else if(typeof b==="number"&&(b&0x3ffffff)===b)return this.yj(this.uG,b)
else{z=this.LK
if(z==null)return
y=z[this.dR(b)]
x=this.qo(y,b)
if(x<0)return
w=y.splice(x,1)[0]
this.AY(w)
return w.gx0()}},
aN:function(a,b){var z,y
z=this.rP
y=this.qs
for(;z!=null;){b.call$2(z.Q5,z.x0)
if(y!==this.qs)throw H.b(new P.UV(this))
z=z.Hx}},
yj:function(a,b){var z
if(a==null)return
z=a[b]
if(z==null)return
this.AY(z)
delete a[b]
return z.gx0()},
tS:function(a,b){var z,y
z=new P.db(a,b,null,null)
if(this.rP==null){this.Jr=z
this.rP=z}else{y=this.Jr
z.TI=y
y.Hx=z
this.Jr=z}this.iI=this.iI+1
this.qs=this.qs+1&67108863
return z},
AY:function(a){var z,y
z=a.gTI()
y=a.gHx()
if(z==null)this.rP=y
else z.Hx=y
if(y==null)this.Jr=z
else y.TI=z
this.iI=this.iI-1
this.qs=this.qs+1&67108863},
dR:function(a){return J.v1(a)&0x3ffffff},
qo:function(a,b){var z,y
if(a==null)return-1
z=a.length
for(y=0;y<z;++y)if(J.de(a[y].gQ5(),b))return y
return-1},
bu:function(a){return P.vW(this)},
$isT8:true},a1:{"":"Tp;a",
call$1:function(a){return J.UQ(this.a,a)}},db:{"":"a;Q5<,x0@,Hx<,TI<"},i5:{"":"mW;rF",
gB:function(a){return this.rF.iI},
gA:function(a){var z=this.rF
z=new P.N6(z,z.qs,null,null)
z.tZ=z.rF.rP
return z},
aN:function(a,b){var z,y,x
z=this.rF
y=z.rP
x=z.qs
for(;y!=null;){b.call$1(y.Q5)
if(x!==z.qs)throw H.b(new P.UV(z))
y=y.Hx}},
$asmW:null},N6:{"":"a;rF,qs,tZ,QH",
gl:function(){return this.QH},
G:function(){var z=this.rF
if(this.qs!==z.qs)throw H.b(new P.UV(z))
else{z=this.tZ
if(z==null){this.QH=null
return!1}else{this.QH=z.Q5
this.tZ=this.tZ.Hx
return!0}}}},mW:{"":"a;",
aN:function(a,b){var z
for(z=this.gA(this);z.G();)b.call$1(z.gl())},
tt:function(a,b){return P.F(this,b,H.W8(this,"mW",0))},
br:function(a){return this.tt(a,!0)},
gB:function(a){var z,y
z=this.gA(this)
for(y=0;z.G();)++y
return y},
Zv:function(a,b){var z,y,x
if(typeof b!=="number"||Math.floor(b)!==b||b<0)throw H.b(new P.bJ("value "+H.d(b)))
for(z=this.gA(this),y=b;z.G();){x=z.gl()
if(y===0)return x;--y}throw H.b(new P.bJ("value "+H.d(b)))}},FN:{"":"a;",
gA:function(a){return new H.a7(a,this.gB(a),0,null)},
Zv:function(a,b){return this.t(a,b)},
aN:function(a,b){var z,y
if(typeof a!=="string"&&(typeof a!=="object"||a===null||a.constructor!==Array&&!H.wV(a,a[init.dispatchPropertyName])))return this.Eq(1,b,a)
z=C.i7(a)
for(y=0;y<z;++y){if(y>=C.i7(a))throw H.e(y)
b.call$1(a[y])
if(z!==C.i7(a))throw H.b(new P.UV(a))}},
Eq:function(a,b,c){var z,y
z=this.gB(c)
for(y=0;y<z;++y){b.call$1(this.t(c,y))
if(z!==this.gB(c))throw H.b(new P.UV(c))}},
bu:function(a){var z,y,x
for(y=0;y<$.lD().length;++y){x=$.lD()
if(y>=x.length)throw H.e(y)
if(x[y]===a)return"[...]"}z=P.p9("")
try{$.lD().push(a)
z.KF("[")
z.We(a,", ")
z.KF("]")}finally{x=$.lD()
if(0>=x.length)throw H.e(0)
x.pop()}return z.gv9()},
$isList:true,
$aszM:null},W0:{"":"Tp;a,b",
call$2:function(a,b){var z=this.a
if(!z.a)this.b.KF(", ")
z.a=!1
z=this.b
z.KF(a)
z.KF(": ")
z.KF(b)}},Sw:{"":"mW;J8,JV,D8,Ei",
gA:function(a){return P.MW(this)},
aN:function(a,b){var z,y,x
z=this.Ei
for(y=this.JV;y!==this.D8;y=(y+1&this.J8.length-1)>>>0){x=this.J8
if(y<0||y>=x.length)throw H.e(y)
b.call$1(x[y])
if(z!==this.Ei)H.vh(new P.UV(this))}},
gB:function(a){return(this.D8-this.JV&this.J8.length-1)>>>0},
bu:function(a){return H.mx(this,"{","}")},
Ux:function(){var z,y,x,w
if(this.JV===this.D8)throw H.b(new P.lj("No elements"))
this.Ei=this.Ei+1
z=this.J8
y=this.JV
x=z.length
if(y<0||y>=x)throw H.e(y)
w=z[y]
this.JV=(y+1&x-1)>>>0
return w},
PN:function(a){var z,y,x
z=this.J8
y=this.D8
x=z.length
if(y<0||y>=x)throw H.e(y)
z[y]=a
this.D8=(y+1&x-1)>>>0
if(this.JV===this.D8)this.Xm()
this.Ei=this.Ei+1},
Xm:function(){var z,y,x,w
z=P.A(this.J8.length*2,H.W8(this,"Sw",0))
H.VM(z,[H.W8(this,"Sw",0)])
y=this.J8
x=this.JV
w=y.length-x
H.qG(z,0,w,y,x)
y=this.JV
x=this.J8
H.qG(z,w,w+y,x,0)
this.JV=0
this.D8=this.J8.length
this.J8=z},
Eo:function(a,b){var z=P.A(8,b)
H.VM(z,[b])
this.J8=z},
$asmW:null,
static:{"":"TN",NZ:function(a,b){var z=new P.Sw(null,0,0,0)
H.VM(z,[b])
z.Eo(a,b)
return z}}},o0:{"":"a;rH,U8,Ei,p1,QH",
gl:function(){return this.QH},
G:function(){var z,y,x
z=this.rH
if(this.Ei!==z.Ei)H.vh(new P.UV(z))
y=this.p1
if(y===this.U8){this.QH=null
return!1}x=z.J8
if(y<0||y>=x.length)throw H.e(y)
this.QH=x[y]
this.p1=(this.p1+1&z.J8.length-1)>>>0
return!0},
static:{MW:function(a){return new P.o0(a,a.D8,a.Ei,a.JV,null)}}}}],["dart.core","dart:core",,P,{hl:function(a){var z,y,x,w,v,u
if(typeof a==="number"&&Math.floor(a)===a||typeof a==="number"||typeof a==="boolean"||null==a)return J.AG(a)
if(typeof a==="string"){z=new P.Rn("")
z.v9="\""
for(y=a.length,x=0;x<y;++x){w=C.xB.j(a,x)
if(w<=31)if(w===10)z.v9=z.v9+"\\n"
else if(w===13)z.v9=z.v9+"\\r"
else if(w===9)z.v9=z.v9+"\\t"
else{z.v9=z.v9+"\\x"
if(w<16)z.v9=z.v9+"0"
else{z.v9=z.v9+"1"
w-=16}v=w<10?48+w:87+w
u=P.O8(1,v,J.im)
u.$builtinTypeInfo=[J.im]
v=H.eT(u)
z.v9=z.v9+v}else if(w===92)z.v9=z.v9+"\\\\"
else if(w===34)z.v9=z.v9+"\\\""
else{u=P.O8(1,w,J.im)
u.$builtinTypeInfo=[J.im]
v=H.eT(u)
z.v9=z.v9+v}}z.v9=z.v9+"\""
return z.v9}return"Instance of '"+H.lh(a)+"'"},ad:function(a,b){return a==null?b==null:a===b},A:function(a,b){if(a==null)return new Array(0)
if(typeof a!=="number"||Math.floor(a)!==a||a<0)throw H.b(new P.AT("Length must be a positive integer: "+H.d(a)+"."))
return H.rD(a)},O8:function(a,b,c){var z,y,x
if(a<0)throw H.b(new P.AT("Length must be a positive integer: "+a+"."))
z=H.rD(a)
if(a!==0&&!0)for(y=z.length,x=0;x<y;++x)z[x]=b
return z},F:function(a,b,c){var z,y,x,w,v,u,t
z=P.A(null,c)
H.VM(z,[c])
for(y=J.GP(a);y.G();)z.push(y.gl())
if(b)return z
x=z.length
w=P.A(x,c)
H.VM(w,[c])
for(y=z.length,v=w.length,u=0;u<x;++u){if(u>=y)throw H.e(u)
t=z[u]
if(u>=v)throw H.e(u)
w[u]=t}return w},CL:{"":"Tp;a",
call$2:function(a,b){var z=this.a
if(z.b>0)z.a.KF(", ")
z.a.KF(a.geu())
z.a.KF(": ")
z.a.KF(P.hl(b))
z.b=z.b+1}},a6:{"":"a;vT<",
W:function(a,b){return new P.a6(0+(this.vT-b.gvT()))},
C:function(a,b){var z=b.gvT()
if(typeof z!=="number")throw H.s(z)
return C.CD.C(this.vT,z)},
D:function(a,b){var z=b.gvT()
if(typeof z!=="number")throw H.s(z)
return C.CD.D(this.vT,z)},
F:function(a,b){var z=b.gvT()
if(typeof z!=="number")throw H.s(z)
return C.CD.F(this.vT,z)},
n:function(a,b){var z
if(b==null)return!1
z=J.x(b)
if(typeof b!=="object"||b===null||!z.$isa6)return!1
return this.vT===b.vT},
giO:function(a){return this.vT&0x1FFFFFFF},
bu:function(a){var z,y,x,w,v
z=new P.DW()
y=this.vT
if(y<0)return"-"+H.d(P.k5(0,0,-y,0,0,0))
x=z.call$1(C.CD.By(C.CD.Z(y,60000000),60))
w=z.call$1(C.CD.By(C.CD.Z(y,1000000),60))
v=new P.P7().call$1(C.CD.By(y,1000000))
return H.d(C.CD.Z(y,3600000000))+":"+H.d(x)+":"+H.d(w)+"."+H.d(v)},
$isa6:true,
static:{"":"Wt,S4,dk,Lo,zj,b2,q9,ts,Do,Cv,kT,IJ,xO,Vk,S8,rG",k5:function(a,b,c,d,e,f){return new P.a6(a*86400000000+b*3600000000+e*60000000+f*1000000+d*1000+c)}}},P7:{"":"Tp;",
call$1:function(a){var z=J.Wx(a)
if(z.F(a,100000))return H.d(a)
if(z.F(a,10000))return"0"+H.d(a)
if(z.F(a,1000))return"00"+H.d(a)
if(z.F(a,100))return"000"+H.d(a)
if(z.D(a,10))return"0000"+H.d(a)
return"00000"+H.d(a)}},DW:{"":"Tp;",
call$1:function(a){if(J.J5(a,10))return H.d(a)
return"0"+H.d(a)}},Ge:{"":"a;",$isGe:true},LK:{"":"Ge;",
bu:function(a){return"Throw of null."}},AT:{"":"Ge;G1",
bu:function(a){var z=this.G1
if(z!=null)return"Illegal argument(s): "+H.d(z)
return"Illegal argument(s)"}},bJ:{"":"AT;G1",
bu:function(a){return"RangeError: "+H.d(this.G1)}},ub:{"":"Ge;G1",
bu:function(a){return"Unsupported operation: "+this.G1}},lj:{"":"Ge;G1",
bu:function(a){return"Bad state: "+this.G1}},UV:{"":"Ge;YA",
bu:function(a){var z=this.YA
if(z==null)return"Concurrent modification during iteration."
return"Concurrent modification during iteration: "+H.d(P.hl(z))+"."}},VS:{"":"a;",
bu:function(a){return"Stack Overflow"},
$isGe:true},t7:{"":"Ge;Wo",
bu:function(a){return"Reading static variable '"+this.Wo+"' during its initialization"}},HG:{"":"a;G1",
bu:function(a){var z=this.G1
if(z==null)return"Exception"
return"Exception: "+H.d(z)},
$isQ4:true},kM:{"":"a;oc",
bu:function(a){return"Expando:"+this.oc},
t:function(a,b){var z=H.of(b,"expando$values")
return z==null?null:H.of(z,this.Ti())},
u:function(a,b,c){var z=H.of(b,"expando$values")
if(z==null){z=new P.a()
H.aw(b,"expando$values",z)}H.aw(z,this.Ti(),c)},
Ti:function(){var z,y
z=H.of(this,"expando$key")
if(z==null){y=$.Ss
$.Ss=y+1
z="expando$key$"+y
H.aw(this,"expando$key",z)}return z},
static:{"":"bZ,rl,Ss",}},AC:{"":"a;"},c8:{"":"a;",
bu:function(a){return"null"}},a:{"":";",
n:function(a,b){return this===b},
giO:function(a){return H.eQ(this)},
bu:function(a){return H.a5(this)}},Rn:{"":"a;v9<",
gB:function(a){return this.v9.length},
KF:function(a){if(typeof a!=="string")return this.fh(1,a)
this.v9=this.v9+a},
fh:function(a,b){var z=typeof b==="string"?b:H.d(b)
this.v9=this.v9+z},
We:function(a,b){var z,y
z=J.GP(a)
if(!z.G())return
if(b.length===0)do{y=z.gl()
y=typeof y==="string"?y:H.d(y)
this.v9=this.v9+y}while(z.G())
else{this.KF(z.gl())
for(;z.G();){this.v9=this.v9+b
y=z.gl()
y=typeof y==="string"?y:H.d(y)
this.v9=this.v9+y}}},
bu:function(a){return this.v9},
PD:function(a){this.v9=a},
static:{p9:function(a){var z=new P.Rn("")
z.PD(a)
return z}}}}],["dart.dom.html","dart:html",,W,{RO:{"":"qh;hA,fV,dW",
X5:function(a,b,c,d){var z=new W.xC(0,this.hA,this.fV,a,this.dW)
H.VM(z,[H.W8(this,"RO",0)])
z.wv()
return z},
$asqh:null},xC:{"":"MO;HX,hA,fV,DR,dW",
Gv:function(){if(this.hA==null)return
this.HU()
this.hA=null
this.DR=null},
wv:function(){var z=this.DR
if(z!=null&&this.HX<=0)J.x0(this.hA,this.fV,z,this.dW)},
HU:function(){var z=this.DR
if(z!=null)J.Io(this.hA,this.fV,z,this.dW)},
$asMO:null},Fk:{"":"a;fV"},qE:{"":"cv;"},Gh:{"":"qE;",
bu:function(a){return a.toString()}},Ny:{"":"qE;R:width}",
gVE:function(a){return a.getContext("2d")}},Nh:{"":"vB;",
bu:function(a){return a.toString()}},cv:{"":"KV;",
bu:function(a){return a.localName}},Fs:{"":"qE;R:width}"},D0:{"":"vB;",
Rt:function(a,b,c,d){return a.addEventListener(b,H.tR(c,1),d)},
ox:function(a,b,c,d){return a.removeEventListener(b,H.tR(c,1),d)}},Yu:{"":"qE;B:length="},tb:{"":"qE;R:width}"},pA:{"":"qE;R:width}"},Mi:{"":"qE;R:width}"},El:{"":"qE;"},KV:{"":"D0;",
bu:function(a){var z=a.nodeValue
return z==null?J.vB.prototype.bu.call(this,a):z}},G7:{"":"qE;R:width}"},lp:{"":"qE;B:length="},aG:{"":"El;R:width}"},K5:{"":"D0;",
nV:function(a,b){return a.requestAnimationFrame(H.tR(b,1))},
rK:function(a){if(!!(a.requestAnimationFrame&&a.cancelAnimationFrame))return
  (function($this) {
   var vendors = ['ms', 'moz', 'webkit', 'o'];
   for (var i = 0; i < vendors.length && !$this.requestAnimationFrame; ++i) {
     $this.requestAnimationFrame = $this[vendors[i] + 'RequestAnimationFrame'];
     $this.cancelAnimationFrame =
         $this[vendors[i]+'CancelAnimationFrame'] ||
         $this[vendors[i]+'CancelRequestAnimationFrame'];
   }
   if ($this.requestAnimationFrame && $this.cancelAnimationFrame) return;
   $this.requestAnimationFrame = function(callback) {
      return window.setTimeout(function() {
        callback(Date.now());
      }, 16 /* 16ms ~= 60fps */);
   };
   $this.cancelAnimationFrame = function(id) { clearTimeout(id); }
  })(a)},
bu:function(a){return a.toString()}}}],["dart.isolate","dart:isolate",,P,{WP:function(){if($.Dz==null)$.Dz=H.Ty()
return $.Dz},rR:{"":"a;"}}],["dart.math","dart:math",,P,{J:function(a,b){if(a>b)return b
if(a<b)return a
if(typeof b==="number"){if(typeof a==="number")if(a===0)return(a+b)*a*b
if(a===0&&C.ON.gzP(b)||isNaN(b))return b
return a}return a},y:function(a,b){if(a>b)return a
if(a<b)return b
if(typeof b==="number"){if(typeof a==="number")if(a===0)return a+b
if(isNaN(b))return b
return a}if(b===0&&C.jn.gzP(a))return b
return a},vY:{"":"a;"}}],["dart.typed_data","dart:typed_data",,P,{xG:{"":"AS+FN;",$isList:true,$aszM:null},Vj:{"":"xG+SU;",$aszM:null},VW:{"":"AS+FN;",$isList:true,$aszM:null},RK:{"":"VW+SU;",$aszM:null},AS:{"":"vB;",
Sv:function(a,b,c){var z=J.Wx(b)
if(z.C(b,0)||z.F(b,c))throw H.b(new P.bJ("value "+H.d(b)+" not in range 0.."+c))
else throw H.b(new P.AT("Invalid list index "+H.d(b)))}},oI:{"":"Vj;",
gB:function(a){return C.i7(a)},
t:function(a,b){var z
if(typeof b!=="number")return this.Nr(1,b,a)
z=C.i7(a)
if(b>>>0!=b||b>=z)this.Sv(a,b,z)
return a[b]},
Nr:function(a,b,c){var z=C.i7(c)
if(b>>>0!=b||J.J5(b,z))this.Sv(c,b,z)
return c[b]},
u:function(a,b,c){var z
if(typeof b!=="number")return this.m4(1,b,c,a)
z=C.i7(a)
if(b>>>0!=b||b>=z)this.Sv(a,b,z)
a[b]=c},
m4:function(a,b,c,d){var z=C.i7(d)
if(b>>>0!=b||J.J5(b,z))this.Sv(d,b,z)
d[b]=c},
$aszM:function(){return[J.VA]},
$asXj:null,
$isList:true,
$isXj:true},n6:{"":"RK;",
gB:function(a){return C.i7(a)},
t:function(a,b){var z
if(typeof b!=="number")return this.Nr(1,b,a)
z=C.i7(a)
if(b>>>0!=b||b>=z)this.Sv(a,b,z)
return a[b]},
Nr:function(a,b,c){var z=C.i7(c)
if(b>>>0!=b||J.J5(b,z))this.Sv(c,b,z)
return c[b]},
u:function(a,b,c){var z
if(typeof b!=="number")return this.m4(1,b,c,a)
z=C.i7(a)
if(b>>>0!=b||b>=z)this.Sv(a,b,z)
a[b]=c},
m4:function(a,b,c,d){var z=C.i7(d)
if(b>>>0!=b||J.J5(b,z))this.Sv(d,b,z)
d[b]=c},
$aszM:function(){return[J.im]},
$asXj:null,
$isList:true,
$isXj:true}}],["particle_cube.dart","../particle_cube.dart",,M,{Iq:function(){var z,y,x,w,v,u,t,s,r,q,p,o
$.qN=document.querySelector("#container")
$.eo=J.uP($.qN)
$.IB=$.qN.parentElement.clientWidth
$.Ii=$.qN.parentElement.clientHeight
J.vP($.qN,$.IB)
for(z=null,y=0;y<5000;++y,z=p){$.pa()
x=Math.random()
w=$.bD().Ev
if(0>=C.i7(w))throw H.e(0)
w=w[0]
$.pa()
v=Math.random()
u=$.bD().Ev
if(1>=C.i7(u))throw H.e(1)
u=u[1]
$.pa()
t=Math.random()
s=$.bD().Ev
if(2>=C.i7(s))throw H.e(2)
s=s[2]
$.pa()
r=Math.random()*255>>>0
r="#"+r.toString(16)
$.pa()
q=Math.random()*255>>>0
r+=q.toString(16)
$.pa()
q=Math.random()*255>>>0
p=new M.mU(null,null,null,null,null,null,r+q.toString(16))
r=new Float32Array(3)
r.$dartCachedLength=r.length
r=new T.An(r)
q=r.Ev
o=C.i7(q)
if(0>=o)throw H.e(0)
q[0]=x*w
if(1>=o)throw H.e(1)
q[1]=v*u
if(2>=o)throw H.e(2)
q[2]=t*s
p.B4=r
r=new Float32Array(2)
r.$dartCachedLength=r.length
r=new T.z3(r)
s=r.Ev
t=C.i7(s)
if(0>=t)throw H.e(0)
s[0]=0
if(1>=t)throw H.e(1)
s[1]=0
p.Fw=r
$.pa()
p.Pb=Math.random()*3.141592653589793*2
M.DV(p.B4,p.Fw)
if(z!=null){p.rZ=z
z.aw=p}if($.Nb==null)$.Nb=p}x=$.eo
x.fillStyle="#FFFFFF"
x.setTransform(1,0,0,1,0,0)
x=window
C.ol.rK(x)
C.ol.nV(x,M.lS)
x=window
C.T1.zc
x=new W.RO(x,C.T1.fV,!1)
H.VM(x,[null])
w=new W.xC(0,x.hA,x.fV,M.hS,x.dW)
H.VM(w,[H.W8(x,"RO",0)])
w.wv()},Vl:function(a){H.ib("onClick "+H.d(a))},E2:function(a){var z,y,x,w,v,u
if(typeof a!=="number")return M.H5(1,a)
z=$.uq
if(typeof z!=="number")return M.H5(2,a,z)
y=a-z
$.uq=a
M.Ie()
$.O3().xI()
z=$.O3()
x=$.bD().Ev
if(0>=C.i7(x))throw H.e(0)
x=x[0]
w=$.bD().Ev
if(1>=C.i7(w))throw H.e(1)
w=w[1]
v=$.bD().Ev
if(2>=C.i7(v))throw H.e(2)
z.px(z,x*0.5,w*0.5,v[2]*0.5)
v=$.O3()
w=$.EG().Ev
if(0>=C.i7(w))throw H.e(0)
v.MT(w[0])
w=$.O3()
v=$.EG().Ev
if(1>=C.i7(v))throw H.e(1)
w.jv(v[1])
v=$.O3()
w=$.EG().Ev
if(2>=C.i7(w))throw H.e(2)
v.cB(w[2])
w=$.O3()
v=$.bD().Ev
if(0>=C.i7(v))throw H.e(0)
v=v[0]
x=$.bD().Ev
if(1>=C.i7(x))throw H.e(1)
x=x[1]
z=$.bD().Ev
if(2>=C.i7(z))throw H.e(2)
w.px(w,-v*0.5,-x*0.5,-z[2]*0.5)
u=$.Nb
for(;u!=null;){u.Am(y)
u=u.aw}z=window
C.ol.rK(z)
C.ol.nV(z,M.lS)},H5:function(a,b,c){switch(a){case 0:case 1:a=0
c=$.uq
case 2:var z,y,x,w,v
a=0
z=J.xH(b,c)
$.uq=b
M.Ie()
$.O3().xI()
c=$.O3()
y=$.bD().Ev
if(0>=C.i7(y))throw H.e(0)
y=y[0]
x=$.bD().Ev
if(1>=C.i7(x))throw H.e(1)
x=x[1]
w=$.bD().Ev
if(2>=C.i7(w))throw H.e(2)
c.px(c,y*0.5,x*0.5,w[2]*0.5)
w=$.O3()
x=$.EG().Ev
if(0>=C.i7(x))throw H.e(0)
w.MT(x[0])
x=$.O3()
w=$.EG().Ev
if(1>=C.i7(w))throw H.e(1)
x.jv(w[1])
w=$.O3()
x=$.EG().Ev
if(2>=C.i7(x))throw H.e(2)
w.cB(x[2])
x=$.O3()
w=$.bD().Ev
if(0>=C.i7(w))throw H.e(0)
w=w[0]
y=$.bD().Ev
if(1>=C.i7(y))throw H.e(1)
y=y[1]
c=$.bD().Ev
if(2>=C.i7(c))throw H.e(2)
x.px(x,-w*0.5,-y*0.5,-c[2]*0.5)
v=$.Nb
for(;v!=null;){v.Am(z)
v=v.aw}c=window
C.ol.rK(c)
C.ol.nV(c,M.lS)}},Ie:function(){$.eo.save()
$.eo.transform(1,0,0,1,0,0)
$.eo.clearRect(0,0,$.IB,$.Ii)
$.eo.restore()},mU:{"":"a;eT,rZ,aw,B4,Fw,Pb,Xw",
Am:function(a){var z,y,x,w,v,u
z=this.B4.Ev
if(0>=C.i7(z))throw H.e(0)
z=z[0]
if(!(z<0)){y=$.bD().Ev
if(0>=C.i7(y))throw H.e(0)
y=z>y[0]
z=y}else z=!0
if(z){z=this.B4
y=$.bD().Ev
if(0>=C.i7(y))throw H.e(0)
y=y[0]
x=this.B4.Ev
if(0>=C.i7(x))throw H.e(0)
x=P.y(0,P.J(y,x[0]))
z=z.Ev
if(0>=C.i7(z))throw H.e(0)
z[0]=x
w=!0}else w=!1
z=this.B4.Ev
if(1>=C.i7(z))throw H.e(1)
z=z[1]
if(!(z<0)){y=$.bD().Ev
if(1>=C.i7(y))throw H.e(1)
y=z>y[1]
z=y}else z=!0
if(z){z=this.B4
y=$.bD().Ev
if(1>=C.i7(y))throw H.e(1)
y=y[1]
x=this.B4.Ev
if(1>=C.i7(x))throw H.e(1)
x=P.y(0,P.J(y,x[1]))
z=z.Ev
if(1>=C.i7(z))throw H.e(1)
z[1]=x
w=!0}if(w)this.Pb=this.Pb+3.141592653589793
M.DV(this.B4,this.Fw)
z=$.eo
z.fillStyle=this.Xw
y=this.Fw.Ev
if(0>=C.i7(y))throw H.e(0)
y=y[0]
if(isNaN(y))H.vh(new P.ub("NaN"))
if(y==Infinity||y==-Infinity)H.vh(new P.ub("Infinity"))
v=y<0?Math.ceil(y):Math.floor(y)
y=v==-0.0?0:v
x=this.Fw.Ev
if(1>=C.i7(x))throw H.e(1)
x=x[1]
if(isNaN(x))H.vh(new P.ub("NaN"))
if(x==Infinity||x==-Infinity)H.vh(new P.ub("Infinity"))
v=x<0?Math.ceil(x):Math.floor(x)
x=v==-0.0?0:v
u=$.tZ
z.fillRect(y,x,u,u)
u=this.B4.Ev
if(0>=C.i7(u))throw H.e(0)
x=u[0]
y=this.Pb
z=Math.cos(y)
if(0>=C.i7(u))throw H.e(0)
u[0]=x+z
z=this.B4.Ev
if(1>=C.i7(z))throw H.e(1)
x=z[1]
u=this.Pb
y=Math.sin(u)
if(1>=C.i7(z))throw H.e(1)
z[1]=x+y},
static:{"":"Nb",DV:function(a,b){var z,y,x,w,v,u
z=$.O3().qT(a)
z.Kj($.O3())
y=z.Ev
if(0>=C.i7(y))throw H.e(0)
x=y[0]
w=$.IB
v=$.bD().Ev
if(0>=C.i7(v))throw H.e(0)
v=v[0]
if(w==null)throw w.W()
u=b.Ev
if(0>=C.i7(u))throw H.e(0)
u[0]=x+(w-v)*0.5
if(1>=C.i7(y))throw H.e(1)
y=y[1]
v=$.Ii
w=$.bD().Ev
if(1>=C.i7(w))throw H.e(1)
w=w[1]
if(v==null)throw v.W()
if(1>=C.i7(u))throw H.e(1)
u[1]=y+(v-w)*0.5}}}},1],["vector_math","package:vector_math/vector_math.dart",,T,{aI:{"":"a;Ev<",
bu:function(a){return"[0] "+H.d(this.aE(0))+"\n[1] "+H.d(this.aE(1))+"\n[2] "+H.d(this.aE(2))+"\n[3] "+H.d(this.aE(3))+"\n"},
t:function(a,b){var z=this.Ev
if(b>>>0!==b||b>=C.i7(z))throw H.e(b)
return z[b]},
u:function(a,b,c){var z=this.Ev
if(b>>>0!==b||b>=C.i7(z))throw H.e(b)
z[b]=c},
aE:function(a){var z,y,x,w,v,u
z=new Float32Array(4)
z.$dartCachedLength=z.length
y=new T.Bp(z)
z=y.Ev
x=this.Ev
w=0+a
v=C.i7(x)
if(w<0||w>=v)throw H.e(w)
w=x[w]
u=C.i7(z)
if(0>=u)throw H.e(0)
z[0]=w
w=4+a
if(w<0||w>=v)throw H.e(w)
w=x[w]
if(1>=u)throw H.e(1)
z[1]=w
w=8+a
if(w<0||w>=v)throw H.e(w)
w=x[w]
if(2>=u)throw H.e(2)
z[2]=w
w=12+a
if(w<0||w>=v)throw H.e(w)
w=x[w]
if(3>=u)throw H.e(3)
z[3]=w
return y},
W:function(a,b){var z,y,x,w,v,u,t
z=new Float32Array(16)
z.$dartCachedLength=z.length
y=new T.aI(z)
z=y.Ev
x=this.Ev
w=C.i7(x)
if(0>=w)throw H.e(0)
v=x[0]
u=b.gEv()
if(0>=C.i7(u))throw H.e(0)
u=u[0]
t=C.i7(z)
if(0>=t)throw H.e(0)
z[0]=v-u
if(1>=w)throw H.e(1)
u=x[1]
v=b.gEv()
if(1>=C.i7(v))throw H.e(1)
v=v[1]
if(1>=t)throw H.e(1)
z[1]=u-v
if(2>=w)throw H.e(2)
v=x[2]
u=b.gEv()
if(2>=C.i7(u))throw H.e(2)
u=u[2]
if(2>=t)throw H.e(2)
z[2]=v-u
if(3>=w)throw H.e(3)
u=x[3]
v=b.gEv()
if(3>=C.i7(v))throw H.e(3)
v=v[3]
if(3>=t)throw H.e(3)
z[3]=u-v
if(4>=w)throw H.e(4)
v=x[4]
u=b.gEv()
if(4>=C.i7(u))throw H.e(4)
u=u[4]
if(4>=t)throw H.e(4)
z[4]=v-u
if(5>=w)throw H.e(5)
u=x[5]
v=b.gEv()
if(5>=C.i7(v))throw H.e(5)
v=v[5]
if(5>=t)throw H.e(5)
z[5]=u-v
if(6>=w)throw H.e(6)
v=x[6]
u=b.gEv()
if(6>=C.i7(u))throw H.e(6)
u=u[6]
if(6>=t)throw H.e(6)
z[6]=v-u
if(7>=w)throw H.e(7)
u=x[7]
v=b.gEv()
if(7>=C.i7(v))throw H.e(7)
v=v[7]
if(7>=t)throw H.e(7)
z[7]=u-v
if(8>=w)throw H.e(8)
v=x[8]
u=b.gEv()
if(8>=C.i7(u))throw H.e(8)
u=u[8]
if(8>=t)throw H.e(8)
z[8]=v-u
if(9>=w)throw H.e(9)
u=x[9]
v=b.gEv()
if(9>=C.i7(v))throw H.e(9)
v=v[9]
if(9>=t)throw H.e(9)
z[9]=u-v
if(10>=w)throw H.e(10)
v=x[10]
u=b.gEv()
if(10>=C.i7(u))throw H.e(10)
u=u[10]
if(10>=t)throw H.e(10)
z[10]=v-u
if(11>=w)throw H.e(11)
u=x[11]
v=b.gEv()
if(11>=C.i7(v))throw H.e(11)
v=v[11]
if(11>=t)throw H.e(11)
z[11]=u-v
if(12>=w)throw H.e(12)
v=x[12]
u=b.gEv()
if(12>=C.i7(u))throw H.e(12)
u=u[12]
if(12>=t)throw H.e(12)
z[12]=v-u
if(13>=w)throw H.e(13)
u=x[13]
v=b.gEv()
if(13>=C.i7(v))throw H.e(13)
v=v[13]
if(13>=t)throw H.e(13)
z[13]=u-v
if(14>=w)throw H.e(14)
v=x[14]
u=b.gEv()
if(14>=C.i7(u))throw H.e(14)
u=u[14]
if(14>=t)throw H.e(14)
z[14]=v-u
if(15>=w)throw H.e(15)
x=x[15]
w=b.gEv()
if(15>=C.i7(w))throw H.e(15)
w=w[15]
if(15>=t)throw H.e(15)
z[15]=x-w
return y},
px:function(a,b,c,d){var z,y,x,w,v,u,t,s,r,q,p,o,n,m,l,k,j,i,h,g,f
z=typeof b==="object"&&b!==null&&!!C.CD.$isBp
y=z?b.gES():1
if(typeof b==="object"&&b!==null&&!!C.CD.$isAn||z){x=C.CD.gx(b)
w=C.CD.gy(b)
v=C.CD.gz(b)}else{v=d
w=c
x=b}z=this.Ev
u=C.i7(z)
if(0>=u)throw H.e(0)
t=z[0]
if(typeof x!=="number")throw H.s(x)
if(4>=u)throw H.e(4)
s=z[4]
if(typeof w!=="number")throw H.s(w)
if(8>=u)throw H.e(8)
r=z[8]
if(typeof v!=="number")throw H.s(v)
if(12>=u)throw H.e(12)
q=z[12]
p=z[1]
o=z[5]
n=z[9]
if(13>=u)throw H.e(13)
m=z[13]
l=z[2]
k=z[6]
j=z[10]
if(14>=u)throw H.e(14)
i=z[14]
h=z[3]
g=z[7]
f=z[11]
if(15>=u)throw H.e(15)
u=z[15]
z[12]=t*x+s*w+r*v+q*y
z[13]=p*x+o*w+n*v+m*y
z[14]=l*x+k*w+j*v+i*y
z[15]=h*x+g*w+f*v+u*y
return this},
MT:function(a){var z,y,x,w,v,u,t,s,r,q,p,o
z=Math.cos(a)
y=Math.sin(a)
x=this.Ev
w=C.i7(x)
if(4>=w)throw H.e(4)
v=x[4]
if(8>=w)throw H.e(8)
u=x[8]
t=x[5]
if(9>=w)throw H.e(9)
s=x[9]
r=x[6]
if(10>=w)throw H.e(10)
q=x[10]
p=x[7]
if(11>=w)throw H.e(11)
w=x[11]
o=-y
x[4]=v*z+u*y
x[5]=t*z+s*y
x[6]=r*z+q*y
x[7]=p*z+w*y
x[8]=v*o+u*z
x[9]=t*o+s*z
x[10]=r*o+q*z
x[11]=p*o+w*z
return this},
jv:function(a){var z,y,x,w,v,u,t,s,r,q,p,o
z=Math.cos(a)
y=Math.sin(a)
x=this.Ev
w=C.i7(x)
if(0>=w)throw H.e(0)
v=x[0]
if(8>=w)throw H.e(8)
u=x[8]
t=x[1]
if(9>=w)throw H.e(9)
s=x[9]
r=x[2]
if(10>=w)throw H.e(10)
q=x[10]
p=x[3]
if(11>=w)throw H.e(11)
w=x[11]
o=-y
x[0]=v*z+u*y
x[1]=t*z+s*y
x[2]=r*z+q*y
x[3]=p*z+w*y
x[8]=v*o+u*z
x[9]=t*o+s*z
x[10]=r*o+q*z
x[11]=p*o+w*z
return this},
cB:function(a){var z,y,x,w,v,u,t,s,r,q,p,o
z=Math.cos(a)
y=Math.sin(a)
x=this.Ev
w=C.i7(x)
if(0>=w)throw H.e(0)
v=x[0]
if(4>=w)throw H.e(4)
u=x[4]
t=x[1]
if(5>=w)throw H.e(5)
s=x[5]
r=x[2]
if(6>=w)throw H.e(6)
q=x[6]
p=x[3]
if(7>=w)throw H.e(7)
w=x[7]
o=-y
x[0]=v*z+u*y
x[1]=t*z+s*y
x[2]=r*z+q*y
x[3]=p*z+w*y
x[4]=v*o+u*z
x[5]=t*o+s*z
x[6]=r*o+q*z
x[7]=p*o+w*z
return this},
xI:function(){var z,y
z=this.Ev
y=C.i7(z)
if(0>=y)throw H.e(0)
z[0]=1
if(1>=y)throw H.e(1)
z[1]=0
if(2>=y)throw H.e(2)
z[2]=0
if(3>=y)throw H.e(3)
z[3]=0
if(4>=y)throw H.e(4)
z[4]=0
if(5>=y)throw H.e(5)
z[5]=1
if(6>=y)throw H.e(6)
z[6]=0
if(7>=y)throw H.e(7)
z[7]=0
if(8>=y)throw H.e(8)
z[8]=0
if(9>=y)throw H.e(9)
z[9]=0
if(10>=y)throw H.e(10)
z[10]=1
if(11>=y)throw H.e(11)
z[11]=0
if(12>=y)throw H.e(12)
z[12]=0
if(13>=y)throw H.e(13)
z[13]=0
if(14>=y)throw H.e(14)
z[14]=0
if(15>=y)throw H.e(15)
z[15]=1
return this},
qT:function(a){var z,y,x,w,v,u,t,s,r,q,p,o,n,m,l,k,j
z=this.Ev
y=C.i7(z)
if(0>=y)throw H.e(0)
x=z[0]
w=a.Ev
v=C.i7(w)
if(0>=v)throw H.e(0)
u=w[0]
if(4>=y)throw H.e(4)
t=z[4]
if(1>=v)throw H.e(1)
s=w[1]
if(8>=y)throw H.e(8)
r=z[8]
if(2>=v)throw H.e(2)
v=w[2]
if(12>=y)throw H.e(12)
q=z[12]
p=z[1]
o=z[5]
n=z[9]
if(13>=y)throw H.e(13)
m=z[13]
l=z[2]
k=z[6]
j=z[10]
if(14>=y)throw H.e(14)
z=z[14]
w[0]=x*u+t*s+r*v+q
w[1]=p*u+o*s+n*v+m
w[2]=l*u+k*s+j*v+z
return a}},z3:{"":"a;Ev<",
bu:function(a){var z,y
z=this.Ev
if(0>=C.i7(z))throw H.e(0)
y="["+H.d(z[0])+","
if(1>=C.i7(z))throw H.e(1)
return y+H.d(z[1])+"]"},
W:function(a,b){var z,y,x,w,v,u,t
z=this.Ev
y=C.i7(z)
if(0>=y)throw H.e(0)
x=z[0]
w=b.gEv()
v=C.i7(w)
if(0>=v)throw H.e(0)
u=w[0]
if(1>=y)throw H.e(1)
z=z[1]
if(1>=v)throw H.e(1)
w=w[1]
v=new Float32Array(2)
v.$dartCachedLength=v.length
v=new T.z3(v)
y=v.Ev
t=C.i7(y)
if(0>=t)throw H.e(0)
y[0]=x-u
if(1>=t)throw H.e(1)
y[1]=z-w
return v},
t:function(a,b){var z=this.Ev
if(b>>>0!==b||b>=C.i7(z))throw H.e(b)
return z[b]},
u:function(a,b,c){var z=this.Ev
if(b>>>0!==b||b>=C.i7(z))throw H.e(b)
z[b]=c},
gB:function(a){var z,y,x
z=this.Ev
y=C.i7(z)
if(0>=y)throw H.e(0)
x=z[0]
if(1>=y)throw H.e(1)
z=z[1]
return Math.sqrt(x*x+z*z)}},An:{"":"a;Ev<",
PJ:function(a,b,c){var z,y
z=this.Ev
y=C.i7(z)
if(0>=y)throw H.e(0)
z[0]=a
if(1>=y)throw H.e(1)
z[1]=b
if(2>=y)throw H.e(2)
z[2]=c
return this},
bu:function(a){var z,y
z=this.Ev
if(0>=C.i7(z))throw H.e(0)
y="["+H.d(z[0])+","
if(1>=C.i7(z))throw H.e(1)
y=y+H.d(z[1])+","
if(2>=C.i7(z))throw H.e(2)
return y+H.d(z[2])+"]"},
W:function(a,b){var z,y,x,w,v,u,t,s,r
z=this.Ev
y=C.i7(z)
if(0>=y)throw H.e(0)
x=z[0]
w=b.gEv()
v=C.i7(w)
if(0>=v)throw H.e(0)
u=w[0]
if(1>=y)throw H.e(1)
t=z[1]
if(1>=v)throw H.e(1)
s=w[1]
if(2>=y)throw H.e(2)
z=z[2]
if(2>=v)throw H.e(2)
w=w[2]
v=new Float32Array(3)
v.$dartCachedLength=v.length
v=new T.An(v)
y=v.Ev
r=C.i7(y)
if(0>=r)throw H.e(0)
y[0]=x-u
if(1>=r)throw H.e(1)
y[1]=t-s
if(2>=r)throw H.e(2)
y[2]=z-w
return v},
t:function(a,b){var z=this.Ev
if(b>>>0!==b||b>=C.i7(z))throw H.e(b)
return z[b]},
u:function(a,b,c){var z=this.Ev
if(b>>>0!==b||b>=C.i7(z))throw H.e(b)
z[b]=c},
gB:function(a){var z,y,x,w
z=this.Ev
y=C.i7(z)
if(0>=y)throw H.e(0)
x=z[0]
if(1>=y)throw H.e(1)
w=z[1]
if(2>=y)throw H.e(2)
z=z[2]
return Math.sqrt(x*x+w*w+z*z)},
Kj:function(a){var z,y,x,w,v,u,t,s,r,q
z=this.Ev
y=C.i7(z)
if(0>=y)throw H.e(0)
x=z[0]
if(1>=y)throw H.e(1)
w=z[1]
if(2>=y)throw H.e(2)
v=z[2]
y=a.Ev
u=C.i7(y)
if(3>=u)throw H.e(3)
t=y[3]
if(7>=u)throw H.e(7)
s=y[7]
if(11>=u)throw H.e(11)
r=y[11]
if(15>=u)throw H.e(15)
q=1/(t*x+s*w+r*v+y[15])
z[0]=(y[0]*x+y[4]*w+y[8]*v+y[12])*q
z[1]=(y[1]*x+y[5]*w+y[9]*v+y[13])*q
z[2]=(y[2]*x+y[6]*w+y[10]*v+y[14])*q
return this},
$isAn:true},Bp:{"":"a;Ev<",
bu:function(a){var z,y
z=this.Ev
if(0>=C.i7(z))throw H.e(0)
y=H.d(z[0])+","
if(1>=C.i7(z))throw H.e(1)
y=y+H.d(z[1])+","
if(2>=C.i7(z))throw H.e(2)
y=y+H.d(z[2])+","
if(3>=C.i7(z))throw H.e(3)
return y+H.d(z[3])},
W:function(a,b){var z,y,x,w,v,u,t,s,r,q
z=this.Ev
y=C.i7(z)
if(0>=y)throw H.e(0)
x=z[0]
w=b.gEv()
v=C.i7(w)
if(0>=v)throw H.e(0)
u=w[0]
if(1>=y)throw H.e(1)
t=z[1]
if(1>=v)throw H.e(1)
s=w[1]
if(2>=y)throw H.e(2)
r=z[2]
if(2>=v)throw H.e(2)
q=w[2]
if(3>=y)throw H.e(3)
z=z[3]
if(3>=v)throw H.e(3)
w=w[3]
v=new Float32Array(4)
v.$dartCachedLength=v.length
v=new T.Bp(v)
y=v.Ev
if(3>=C.i7(y))throw H.e(3)
y[3]=z-w
y[2]=r-q
y[1]=t-s
y[0]=x-u
return v},
t:function(a,b){var z=this.Ev
if(b>>>0!==b||b>=C.i7(z))throw H.e(b)
return z[b]},
u:function(a,b,c){var z=this.Ev
if(b>>>0!==b||b>=C.i7(z))throw H.e(b)
z[b]=c},
gB:function(a){var z,y,x,w,v
z=this.Ev
y=C.i7(z)
if(0>=y)throw H.e(0)
x=z[0]
if(1>=y)throw H.e(1)
w=z[1]
if(2>=y)throw H.e(2)
v=z[2]
if(3>=y)throw H.e(3)
z=z[3]
return Math.sqrt(x*x+w*w+v*v+z*z)},
gES:function(){var z=this.Ev
if(3>=C.i7(z))throw H.e(3)
return z[3]},
$isBp:true}}],])
I.$finishClasses($$,$,null)
$$=null
init.globalFunctions.NB=H.NB=new H.fo(H.Mg,"NB")
init.globalFunctions.Eu=H.Eu=new H.E8(H.Ju,"Eu")
init.globalFunctions.eH=H.eH=new H.oL(H.ft,"eH")
init.globalFunctions.qA=H.qA=new H.v8(H.Ph,"qA")
init.globalFunctions.nY=H.nY=new H.EE(H.f4,"nY")
init.globalFunctions.D3=H.D3=new H.Q3(H.vK,"D3")
init.globalFunctions.Bi=H.Bi=new H.Pi(H.mv,"Bi")
init.globalFunctions.tu=H.tu=new H.jU(H.Tx,"tu")
init.globalFunctions.DA=H.DA=new H.eB(H.xb,"DA")
init.globalFunctions.dq=H.dq=new H.r7(H.jm,"dq")
init.globalFunctions.qZ=P.qZ=new P.EN(P.BG,"qZ")
init.globalFunctions.iv=P.iv=new P.Xk(P.Ou,"iv")
init.globalFunctions.py=P.py=new P.Wv(P.T9,"py")
init.globalFunctions.N3=P.N3=new P.vb(P.ad,"N3")
init.globalFunctions.eE=M.eE=new M.FL(M.Iq,"eE")
init.globalFunctions.hS=M.hS=new M.CW(M.Vl,"hS")
init.globalFunctions.lS=M.lS=new M.pR(M.E2,"lS")
J.RE=function(a){if(a==null)return a
if(typeof a!="object")return a
if(a instanceof P.a)return a
return J.ks(a)}
J.U6=function(a){if(typeof a=="string")return J.O.prototype
if(a==null)return a
if(a.constructor==Array)return J.Q.prototype
if(typeof a!="object")return a
if(a instanceof P.a)return a
return J.ks(a)}
J.Wx=function(a){if(typeof a=="number")return J.P.prototype
if(a==null)return a
if(!(a instanceof P.a))return J.kd.prototype
return a}
J.rY=function(a){if(typeof a=="string")return J.O.prototype
if(a==null)return a
if(!(a instanceof P.a))return J.kd.prototype
return a}
J.w1=function(a){if(a==null)return a
if(a.constructor==Array)return J.Q.prototype
if(typeof a!="object")return a
if(a instanceof P.a)return a
return J.ks(a)}
J.x=function(a){if(typeof a=="number"){if(Math.floor(a)==a)return J.im.prototype
return J.VA.prototype}if(typeof a=="string")return J.O.prototype
if(a==null)return J.PE.prototype
if(typeof a=="boolean")return J.kn.prototype
if(a.constructor==Array)return J.Q.prototype
if(typeof a!="object")return a
if(a instanceof P.a)return a
return J.ks(a)}
C.Im=new H.NU()
C.Ku=new J.kd()
C.JB=new P.vY()
C.RT=new P.a6(0)
C.T1=new W.Fk("click")
C.Nm=J.Q.prototype
C.ON=J.VA.prototype
C.jn=J.im.prototype
C.CD=J.P.prototype
C.xB=J.O.prototype
C.i7=    ((typeof version == "function" && typeof os == "object" && "system" in os)
    || (typeof navigator == "object"
        && navigator.userAgent.indexOf('Chrome') != -1))
        ? function(x) { return x.$dartCachedLength || x.length; }
        : function(x) { return x.length; };

I.makeConstantList = function(list) {
  list.immutable$list = true;
  list.fixed$length = true;
  return list;
};
C.xD=I.makeConstantList([])
C.ol=W.K5.prototype
$.Dz=null
$.b9=1
$.te="$cachedFunction"
$.eb="$cachedInvocation"
$.NP=null
$.kP=null
$.LI=null
$.TH=!1
$.Ss=0
$.tZ=2
$.qN=null
$.eo=null
$.IB=null
$.Ii=null
$.uq=0
$.Nb=null
J.AG=function(a){return J.x(a).bu(a)}
J.GP=function(a){return J.w1(a).gA(a)}
J.Io=function(a,b,c,d){return J.RE(a).ox(a,b,c,d)}
J.J5=function(a,b){if(typeof a=="number"&&typeof b=="number")return a>=b
return J.Wx(a).F(a,b)}
J.Oq=function(a){return J.Wx(a).Hp(a)}
J.UQ=function(a,b){if(a.constructor==Array||typeof a=="string"||H.wV(a,a[init.dispatchPropertyName]))if(b>>>0===b&&b<a.length)return a[b]
return J.U6(a).t(a,b)}
J.de=function(a,b){if(a==null)return b==null
if(typeof a!="object")return b!=null&&a===b
return J.x(a).n(a,b)}
J.kH=function(a,b){return J.w1(a).aN(a,b)}
J.kW=function(a,b,c){if((a.constructor==Array||H.wV(a,a[init.dispatchPropertyName]))&&!a.immutable$list&&b>>>0===b&&b<a.length)return a[b]=c
return J.w1(a).u(a,b,c)}
J.uP=function(a){return J.RE(a).gVE(a)}
J.v1=function(a){return J.x(a).giO(a)}
J.vP=function(a,b){return J.RE(a).sR(a,b)}
J.x0=function(a,b,c,d){return J.RE(a).Rt(a,b,c,d)}
J.xH=function(a,b){if(typeof a=="number"&&typeof b=="number")return a-b
return J.Wx(a).W(a,b)}
$.Au=[]
I.$lazy($,"globalThis","DX","jk",function(){return function() { return this; }()})
I.$lazy($,"globalWindow","cO","C5",function(){return $.jk().window})
I.$lazy($,"globalWorker","zA","Nl",function(){return $.jk().Worker})
I.$lazy($,"globalPostMessageDefined","Wd","Iz",function(){return $.jk().postMessage!==void 0})
I.$lazy($,"thisScript","Kb","Rs",function(){return H.Td()})
I.$lazy($,"workerIds","rS","p6",function(){return new P.kM(null)})
I.$lazy($,"noSuchMethodPattern","lm","WD",function(){return H.cM(H.S7({ toString: function() { return "$receiver$"; } }))})
I.$lazy($,"notClosurePattern","k1","OI",function(){return H.cM(H.S7({ $method$: null, toString: function() { return "$receiver$"; } }))})
I.$lazy($,"nullCallPattern","Re","PH",function(){return H.cM(H.S7(null))})
I.$lazy($,"nullLiteralCallPattern","fN","D1",function(){return H.cM(H.pb())})
I.$lazy($,"undefinedCallPattern","qi","rx",function(){return H.cM(H.S7(void 0))})
I.$lazy($,"undefinedLiteralCallPattern","rZ","Kr",function(){return H.cM(H.u9())})
I.$lazy($,"nullPropertyPattern","BX","zO",function(){return H.cM(H.Mj(null))})
I.$lazy($,"nullLiteralPropertyPattern","tt","PB",function(){return H.cM(H.Qd())})
I.$lazy($,"undefinedPropertyPattern","dt","eA",function(){return H.cM(H.Mj(void 0))})
I.$lazy($,"undefinedLiteralPropertyPattern","A7","ko",function(){return H.cM(H.m0())})
I.$lazy($,"getTypeNameOf","Zv","nn",function(){return H.VP()})
I.$lazy($,"_toStringList","Ml","RM",function(){return P.A(null,null)})
I.$lazy($,"_stackTraceExpando","MG","ij",function(){return new P.kM("asynchronous error")})
I.$lazy($,"_asyncCallbacks","r1","P8",function(){return P.NZ(null,{func:"X0",void:true})})
I.$lazy($,"_current","kx","o8",function(){return new P.Ec(null,0,0,!1)})
I.$lazy($,"_toStringList","Pl","lD",function(){return P.A(null,null)})
I.$lazy($,"_toStringList","yu","tw",function(){return P.A(null,null)})
I.$lazy($,"_rotation","Ej","EG",function(){var z=new Float32Array(3)
z.$dartCachedLength=z.length
z=new T.An(z)
z.PJ(0.005,0.005,0.005)
return z})
I.$lazy($,"_bounds","Up","bD",function(){var z,y,x
z=J.Oq($.IB)
y=J.Oq($.Ii)
x=new Float32Array(3)
x.$dartCachedLength=x.length
x=new T.An(x)
x.PJ(z,y,100)
return x})
I.$lazy($,"matrix4","G2","O3",function(){var z=new Float32Array(16)
z.$dartCachedLength=z.length
z=new T.aI(z)
z.xI()
return z})
I.$lazy($,"random","Y4","pa",function(){return C.JB})
H.VQ("AudioProcessingEvent|AutocompleteErrorEvent|BeforeLoadEvent|CSSFontFaceLoadEvent|CanvasGradient|CanvasPattern|CanvasRenderingContext|CanvasRenderingContext2D|CloseEvent|CompositionEvent|CustomEvent|DOMError|DeviceMotionEvent|DeviceOrientationEvent|DragEvent|ErrorEvent|Event|FileError|FocusEvent|HashChangeEvent|IDBVersionChangeEvent|KeyboardEvent|MIDIConnectionEvent|MIDIMessageEvent|MSPointerEvent|MediaError|MediaKeyError|MediaKeyEvent|MediaKeyMessageEvent|MediaKeyNeededEvent|MediaStreamEvent|MediaStreamTrackEvent|MessageEvent|MouseEvent|MouseScrollEvent|MouseWheelEvent|MutationEvent|Navigator|NavigatorUserMediaError|OfflineAudioCompletionEvent|OverflowEvent|PageTransitionEvent|PointerEvent|PopStateEvent|PositionError|ProgressEvent|RTCDTMFToneChangeEvent|RTCDataChannelEvent|RTCIceCandidateEvent|ResourceProgressEvent|SQLError|SVGAnimatedLength|SVGAnimatedLengthList|SVGAnimatedNumber|SVGAnimatedNumberList|SVGAnimatedTransformList|SVGZoomEvent|SecurityPolicyViolationEvent|SpeechInputEvent|SpeechRecognitionError|SpeechRecognitionEvent|SpeechSynthesisEvent|StorageEvent|TextEvent|TouchEvent|TrackEvent|TransitionEvent|UIEvent|WebGLContextEvent|WebKitAnimationEvent|WebKitTransitionEvent|WheelEvent|XMLHttpRequestProgressEvent",J.vB)
H.VQ("HTMLAppletElement|HTMLAreaElement|HTMLBRElement|HTMLBaseElement|HTMLBaseFontElement|HTMLBodyElement|HTMLButtonElement|HTMLContentElement|HTMLDListElement|HTMLDataListElement|HTMLDetailsElement|HTMLDialogElement|HTMLDirectoryElement|HTMLDivElement|HTMLFieldSetElement|HTMLFontElement|HTMLFrameElement|HTMLFrameSetElement|HTMLHRElement|HTMLHeadElement|HTMLHeadingElement|HTMLHtmlElement|HTMLKeygenElement|HTMLLIElement|HTMLLabelElement|HTMLLegendElement|HTMLLinkElement|HTMLMapElement|HTMLMarqueeElement|HTMLMenuElement|HTMLMetaElement|HTMLMeterElement|HTMLModElement|HTMLOListElement|HTMLOptGroupElement|HTMLOptionElement|HTMLOutputElement|HTMLParagraphElement|HTMLParamElement|HTMLPreElement|HTMLProgressElement|HTMLQuoteElement|HTMLScriptElement|HTMLShadowElement|HTMLSourceElement|HTMLSpanElement|HTMLStyleElement|HTMLTableCaptionElement|HTMLTableCellElement|HTMLTableColElement|HTMLTableDataCellElement|HTMLTableElement|HTMLTableHeaderCellElement|HTMLTableRowElement|HTMLTableSectionElement|HTMLTemplateElement|HTMLTextAreaElement|HTMLTitleElement|HTMLTrackElement|HTMLUListElement|HTMLUnknownElement",W.qE)
H.MT("HTMLElement",W.qE)
H.VQ("HTMLAnchorElement",W.Gh)
H.VQ("HTMLCanvasElement",W.Ny)
H.VQ("DOMException",W.Nh)
H.VQ("SVGAElement|SVGAltGlyphDefElement|SVGAltGlyphElement|SVGAltGlyphItemElement|SVGAnimateColorElement|SVGAnimateElement|SVGAnimateMotionElement|SVGAnimateTransformElement|SVGAnimationElement|SVGCircleElement|SVGClipPathElement|SVGComponentTransferFunctionElement|SVGCursorElement|SVGDefsElement|SVGDescElement|SVGElement|SVGEllipseElement|SVGFEBlendElement|SVGFEColorMatrixElement|SVGFEComponentTransferElement|SVGFECompositeElement|SVGFEConvolveMatrixElement|SVGFEDiffuseLightingElement|SVGFEDisplacementMapElement|SVGFEDistantLightElement|SVGFEDropShadowElement|SVGFEFloodElement|SVGFEFuncAElement|SVGFEFuncBElement|SVGFEFuncGElement|SVGFEFuncRElement|SVGFEGaussianBlurElement|SVGFEImageElement|SVGFEMergeElement|SVGFEMergeNodeElement|SVGFEMorphologyElement|SVGFEOffsetElement|SVGFEPointLightElement|SVGFESpecularLightingElement|SVGFESpotLightElement|SVGFETileElement|SVGFETurbulenceElement|SVGFilterElement|SVGFontElement|SVGFontFaceElement|SVGFontFaceFormatElement|SVGFontFaceNameElement|SVGFontFaceSrcElement|SVGFontFaceUriElement|SVGForeignObjectElement|SVGGElement|SVGGlyphElement|SVGGlyphRefElement|SVGGradientElement|SVGGraphicsElement|SVGHKernElement|SVGImageElement|SVGLineElement|SVGLinearGradientElement|SVGMPathElement|SVGMarkerElement|SVGMaskElement|SVGMetadataElement|SVGMissingGlyphElement|SVGPathElement|SVGPatternElement|SVGPolygonElement|SVGPolylineElement|SVGRadialGradientElement|SVGRectElement|SVGSVGElement|SVGScriptElement|SVGSetElement|SVGStopElement|SVGStyleElement|SVGSwitchElement|SVGSymbolElement|SVGTRefElement|SVGTSpanElement|SVGTextContentElement|SVGTextElement|SVGTextPathElement|SVGTextPositioningElement|SVGTitleElement|SVGUseElement|SVGVKernElement|SVGViewElement",W.cv)
H.MT("Element",W.cv)
H.VQ("HTMLEmbedElement",W.Fs)
H.MT("EventTarget",W.D0)
H.VQ("HTMLFormElement",W.Yu)
H.VQ("HTMLIFrameElement",W.tb)
H.VQ("HTMLImageElement",W.pA)
H.VQ("HTMLInputElement",W.Mi)
H.VQ("HTMLAudioElement",W.El)
H.MT("HTMLMediaElement",W.El)
H.VQ("Document|HTMLDocument",W.KV)
H.MT("Node",W.KV)
H.VQ("HTMLObjectElement",W.G7)
H.VQ("HTMLSelectElement",W.lp)
H.VQ("HTMLVideoElement",W.aG)
H.VQ("DOMWindow|Window",W.K5)
H.XJ("ArrayBufferView",P.AS,[P.xG,P.Vj,P.VW,P.RK])
H.VQ("Float32Array",P.oI)
H.MT("Uint8Array",P.n6)

init.functionAliases={}
init.metadata=[];$=null
I = I.$finishIsolateConstructor(I)
$=new I()
function convertToFastObject(properties) {
  function makeConstructor() {
    var str = "{\n";
    var hasOwnProperty = Object.prototype.hasOwnProperty;
    for (var property in properties) {
      if (hasOwnProperty.call(properties, property)) {
        str += "this." + property + "= properties." + property + ";\n";
      }
    }
    str += "}\n";
    return new Function("properties", str);
  };
  var constructor = makeConstructor();
  return makeConstructor.prototype = new constructor(properties);
}
A = convertToFastObject(A)
B = convertToFastObject(B)
C = convertToFastObject(C)
D = convertToFastObject(D)
E = convertToFastObject(E)
F = convertToFastObject(F)
G = convertToFastObject(G)
H = convertToFastObject(H)
J = convertToFastObject(J)
K = convertToFastObject(K)
L = convertToFastObject(L)
M = convertToFastObject(M)
N = convertToFastObject(N)
O = convertToFastObject(O)
P = convertToFastObject(P)
Q = convertToFastObject(Q)
R = convertToFastObject(R)
S = convertToFastObject(S)
T = convertToFastObject(T)
U = convertToFastObject(U)
V = convertToFastObject(V)
W = convertToFastObject(W)
X = convertToFastObject(X)
Y = convertToFastObject(Y)
Z = convertToFastObject(Z)
!function(){var z=Object.prototype
for(var y=0;;y++){var x="___dart_dispatch_record_ZxYxX_0_"
if(y>0)x=rootProperty+"_"+y
if(!(x in z))return init.dispatchPropertyName=x}}()
;(function (callback) {
  if (typeof document === "undefined") {
    callback(null);
    return;
  }
  if (document.currentScript) {
    callback(document.currentScript);
    return;
  }

  var scripts = document.scripts;
  function onLoad(event) {
    for (var i = 0; i < scripts.length; ++i) {
      scripts[i].removeEventListener("load", onLoad, false);
    }
    callback(event.target);
  }
  for (var i = 0; i < scripts.length; ++i) {
    scripts[i].addEventListener("load", onLoad, false);
  }
})(function(currentScript) {
  init.currentScript = currentScript;

  if (typeof dartMainRunner === "function") {
    dartMainRunner(function() { H.Rq(M.eE); });
  } else {
    H.Rq(M.eE);
  }
})
function init(){I.p={}
function generateAccessor(a,b){var x=a.length
var w=a.charCodeAt(x-1)
var v=false
if(w==45){x--
w=a.charCodeAt(x-1)
a=a.substring(0,x)
v=true}w=w>=60&&w<=64?w-59:w>=123&&w<=126?w-117:w>=37&&w<=43?w-27:0
if(w){var u=w&3
var t=w>>2
var s=a=a.substring(0,x-1)
var r=a.indexOf(":")
if(r>0){s=a.substring(0,r)
a=a.substring(r+1)}if(u){var q=u&2?"r":""
var p=u&1?"this":"r"
var o="return "+p+"."+a
b["g"+s]=new Function(q,o)
if(v){b["g"+s].$reflectable=1}}if(t){var q=t&2?"r,v":"v"
var p=t&1?"this":"r"
var o=p+"."+a+"=v"
b["s"+s]=new Function(q,o)
if(v){b["s"+s].$reflectable=1}}}return a}I.p.$generateAccessor=generateAccessor
function defineClass(a,b,c,d){var x
if(typeof c=="function"){x=c}else{var w="function "+b+"("
var v=""
for(var u=0;u<c.length;u++){if(u!=0)w+=", "
var t=generateAccessor(c[u],d)
var s="parameter_"+t
w+=s
v+="this."+t+" = "+s+";\n"}w+=") {"+v+"}\nreturn "+b
x=new Function(w)()}x.prototype=d
x.builtin$cls=a
return x}var z=false
var y=defineClass("c","c",["f<"],{}).prototype
if(y.__proto__){y.__proto__={}
if(typeof y.get$f!="undefined")z=true}I.$finishClasses=function(a,b,c){var x={}
if(!init.allClasses)init.allClasses={}
var w=init.allClasses
var v=Object.prototype.hasOwnProperty
for(var u in a){if(v.call(a,u)){var t=a[u]
var s=b
if(t instanceof Array){s=t[0]||b
t=t[1]}var r=t[""],q,p=u,o=r
if(typeof r=="string"){var n=r.split("/")
if(n.length==2){p=n[0]
o=n[1]}}if(typeof o=="string"){var m=o.split(";")
o=m[1]==""?[]:m[1].split(",")
q=m[0]}else{q=t.super
if(!!t.$name)p=t.$name}if(q&&q.indexOf("+")>0){m=q.split("+")
q=m[0]
var l=a[m[1]]
if(l instanceof Array)l=l[1]
for(var k in l){if(v.call(l,k)&&!v.call(t,k))t[k]=l[k]}}var j=defineClass(p,u,o,t)
w[u]=j
s[u]=j
if(q)x[u]=q}}var i={}
function finishClass(a2){var h=Object.prototype.hasOwnProperty
if(h.call(i,a2))return
i[a2]=true
var g=x[a2]
if(!g||typeof g!="string")return
finishClass(g)
var f=w[a2]
var e=w[g]
if(!e)e=c[g]
var d=f.prototype
if(z){d.__proto__=e.prototype
d.constructor=f}else{function y(){}y.prototype=e.prototype
var a0=new y()
f.prototype=a0
a0.constructor=f
for(var a1 in d){if(!a1)continue
if(h.call(d,a1)){a0[a1]=d[a1]}}}}for(var u in x)finishClass(u)}
I.$lazy=function(a,b,c,d,e){var x=new Function("{ return this."+c+";}")
var w={}
var v={}
a[c]=w
a[d]=function(){var u=$[c]
try{if(u===w){$[c]=v
try{u=$[c]=e()}finally{if(u===w){if($[c]===v){$[c]=null}}}}else{if(u===v)H.ag(b)}return u}finally{$[d]=x}}}
I.$finishIsolateConstructor=function(a){var x=a.p
var w=a.prototype
var v="{\n"
v+="var properties = arguments.callee.p;\n"
var u=Object.prototype.hasOwnProperty
for(var t in x){if(u.call(x,t)){v+="this."+t+"= properties."+t+";\n"}}v+="}\n"
var s=new Function(v)
s.prototype=w
w.constructor=s
s.p=x
s.makeConstantList=a.makeConstantList
s.$finishClasses=a.$finishClasses
return s}}
})()
//# sourceMappingURL=particle_cube.js.map
//@ sourceMappingURL=particle_cube.js.map
